### ISSUE TITLE
HyperDriveStep transient failure with "Failed to upload outputs due to: {ex}" & Aether stacktrace

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#1042]
## Background

I've never seen this error before. I failed. I ran it again and it went away.
File this under ["transient" issue](https://github.com/Azure/MachineLearningNotebooks/issues?q=is%3Aissue+transient). If you have seen this error and find this issue, respond with your experience details!
cc: @swatig007 @rastala 

Region: West US II

## Run IDs
PipelineRun: `a3f19685-7aad-4314-b47b-626d4fe3c502`
HyperDriveStep: `475d75f5-a1d9-40b3-9544-439f580ab50b`
HyperDriveRun: `HD_a2ee7e22-086c-4fef-9c56-ccd4edd41e42`
ChildRun: `HD_a2ee7e22-086c-4fef-9c56-ccd4edd41e42_0`

### "top-level" error message
`Failed to upload outputs due to: {ex}`

### `logs/azureml/execution_logs.txt`
`Failed to upload outputs and mark job as failed. Error: Failure in GetStorageMsi while calling service WorkspaceResource`
```
[2020-07-08 18:26:27Z] RunId:[475d75f5-a1d9-40b3-9544-439f580ab50b] ParentRunId:[a3f19685-7aad-4314-b47b-626d4fe3c502] ComputeTarget:[AmlCompute]
[2020-07-08 18:26:43Z] Current job status is: Running
[2020-07-08 18:27:00Z] Current job status is: Running
[2020-07-08 18:27:41Z] Current job status is: Running
[2020-07-08 18:27:56Z] Current job status is: Running
[2020-07-08 18:28:12Z] Current job status is: Running
[2020-07-08 18:28:29Z] Current job status is: Running
[2020-07-08 18:29:24Z] Current job status is: Completed
[2020-07-08 18:29:24Z] Job completed successfully.
[2020-07-08 18:31:05Z] Failed to upload outputs and mark job as failed. Error: Failure in GetStorageMsi while calling service WorkspaceResource; HttpMethod: GET; Response StatusCode: ; Exception type: System.Threading.Tasks.TaskCanceledException|-System.IO.IOException|-System.Net.Sockets.SocketException, stack trace:    at Microsoft.Aether.BlueBox.WorkspaceResourcesClient.WorkspaceResourcesClient.GetStorageMsiAsync(WorkspaceIdentity workspaceIdentity, CreatedBy createdBy, CancellationToken cancellationToken) in d:\dbs\sh\Ae\0625_091617\cmd\3\src\aether\platform\backendV2\BlueBox\WorkspaceResourcesClient\Microsoft.Aether.BlueBox.WorkspaceResourcesClient\WorkspaceResourcesClient.cs:line 217
   at Microsoft.Aether.HyperDriveCloudK8s.JobProcessing.JobProcessor.CreateAzureBlobStorageAsync(HyperDriveJobMetadata job, String dataStoreName) in d:\dbs\sh\Ae\0625_091617\cmd\s\src\aether\platform\backendV2\BlueBox\Clouds\HyperDriveCloudK8s\HyperDriveCloudK8s.JobProcessing\JobProcessor.cs:line 427
   at Microsoft.Aether.HyperDriveCloudK8s.JobProcessing.JobProcessor.UploadHyperDriveMetricsAsync(HyperDriveJobMetadata job) in d:\dbs\sh\Ae\0625_091617\cmd\s\src\aether\platform\backendV2\BlueBox\Clouds\HyperDriveCloudK8s\HyperDriveCloudK8s.JobProcessing\JobProcessor.cs:line 410
   at Microsoft.Aether.HyperDriveCloudK8s.JobProcessing.JobProcessor.CheckJobStatusAsync(HyperDriveJobMetadata job) in d:\dbs\sh\Ae\0625_091617\cmd\s\src\aether\platform\backendV2\BlueBox\Clouds\HyperDriveCloudK8s\HyperDriveCloudK8s.JobProcessing\JobProcessor.cs:line 307
```
### `logs/azureml/stdoutlogs.txt`
contains metrics for all 5 runs
```
[2020-07-08 18:29:25Z] Metrics for HyperDrive run:
[2020-07-08 18:29:25Z] {"HD_a2ee7e22-086c-4fef-9c56-ccd4edd41e42_0":{"Arguments":["Namespace(boosting_type='gbdt', colsample_bytree=0.4, data_name='deal_data4', importance_type='split', input_dir='/mnt/batch/tasks/shared/LS_root/jobs/avadevitsmlsvc/azureml/hd_a2ee7e22-086c-4fef-9c56-ccd4edd41e42_0/mounts/deal_pipeline_blob/azureml/4130d7d7-3ebf-406f-951c-348f5754ed88/split_data4', learning_rate=0.1, max_bin=100, max_depth=8, min_child_samples=325, min_child_weight=2, min_split_gain=0.9473684210526315, model_name='deal_model4', n_estimators=450, n_jobs=1, num_leaves=180, objective=None, output_dir='c:\\\\\\\\temp\\\\output', random_state=None, reg_alpha=0.7894736842105263, reg_lambda=0.05263157894736842, silent=True, subsample=0.9, subsample_for_bin=200000, subsample_freq=0, verbose=-10)"],"majority_obs":[1007],"minority obs":[3479],"precision":[0.92289719626168221],"geometric mean":[0.7843522351391311],"recall":[0.95641646489104115],"LIFT":[1.2120877312583747],"f1":[0.93935790725326984]},"HD_a2ee7e22-086c-4fef-9c56-ccd4edd41e42_1":{"Arguments":["Namespace(boosting_type='gbdt', colsample_bytree=0.3, data_name='deal_data4', importance_type='split', input_dir='/mnt/batch/tasks/shared/LS_root/jobs/avadevitsmlsvc/azureml/hd_a2ee7e22-086c-4fef-9c56-ccd4edd41e42_1/mounts/deal_pipeline_blob/azureml/4130d7d7-3ebf-406f-951c-348f5754ed88/split_data4', learning_rate=0.04, max_bin=150, max_depth=5, min_child_samples=200, min_child_weight=2, min_split_gain=0.9473684210526315, model_name='deal_model4', n_estimators=500, n_jobs=1, num_leaves=98, objective=None, output_dir='c:\\\\\\\\temp\\\\output', random_state=None, reg_alpha=0.7894736842105263, reg_lambda=0.05263157894736842, silent=True, subsample=1.0, subsample_for_bin=200000, subsample_freq=0, verbose=-10)"],"majority_obs":[1007],"minority obs":[3479],"precision":[0.9242424242424242],"geometric mean":[0.7891350418398223],"recall":[0.96004842615012109],"f1":[0.94180522565320657],"LIFT":[1.2084776412173968]},"HD_a2ee7e22-086c-4fef-9c56-ccd4edd41e42_2":{"Arguments":["Namespace(boosting_type='gbdt', colsample_bytree=0.3, data_name='deal_data4', importance_type='split', input_dir='/mnt/batch/tasks/shared/LS_root/jobs/avadevitsmlsvc/azureml/hd_a2ee7e22-086c-4fef-9c56-ccd4edd41e42_2/mounts/deal_pipeline_blob/azureml/4130d7d7-3ebf-406f-951c-348f5754ed88/split_data4', learning_rate=0.03, max_bin=60, max_depth=5, min_child_samples=75, min_child_weight=2, min_split_gain=0.9473684210526315, model_name='deal_model4', n_estimators=300, n_jobs=1, num_leaves=175, objective=None, output_dir='c:\\\\\\\\temp\\\\output', random_state=None, reg_alpha=0.7894736842105263, reg_lambda=0.05263157894736842, silent=True, subsample=0.6, subsample_for_bin=200000, subsample_freq=0, verbose=-10)"],"majority_obs":[1007],"recall":[0.96246973365617439],"f1":[0.93916125221500291],"minority obs":[3479],"precision":[0.916955017301038],"geometric mean":[0.76673784202646011],"LIFT":[1.204994650599696]},"HD_a2ee7e22-086c-4fef-9c56-ccd4edd41e42_3":{"Arguments":["Namespace(boosting_type='gbdt', colsample_bytree=0.8, data_name='deal_data4', importance_type='split', input_dir='/mnt/batch/tasks/shared/LS_root/jobs/avadevitsmlsvc/azureml/hd_a2ee7e22-086c-4fef-9c56-ccd4edd41e42_3/mounts/deal_pipeline_blob/azureml/4130d7d7-3ebf-406f-951c-348f5754ed88/split_data4', learning_rate=0.03, max_bin=140, max_depth=7, min_child_samples=125, min_child_weight=2, min_split_gain=0.9473684210526315, model_name='deal_model4', n_estimators=600, n_jobs=1, num_leaves=85, objective=None, output_dir='c:\\\\\\\\temp\\\\output', random_state=None, reg_alpha=0.7894736842105263, reg_lambda=0.05263157894736842, silent=True, subsample=0.4, subsample_for_bin=200000, subsample_freq=0, verbose=-10)"],"precision":[0.92227378190255216],"minority obs":[3479],"majority_obs":[1007],"recall":[0.96246973365617439],"f1":[0.94194312796208524],"geometric mean":[0.78351746240885656],"LIFT":[1.2092243064266752]},"HD_a2ee7e22-086c-4fef-9c56-ccd4edd41e42_4":{"Arguments":["Namespace(boosting_type='gbdt', colsample_bytree=0.8, data_name='deal_data4', importance_type='split', input_dir='/mnt/batch/tasks/shared/LS_root/jobs/avadevitsmlsvc/azureml/hd_a2ee7e22-086c-4fef-9c56-ccd4edd41e42_4/mounts/deal_pipeline_blob/azureml/4130d7d7-3ebf-406f-951c-348f5754ed88/split_data4', learning_rate=0.04, max_bin=180, max_depth=3, min_child_samples=875, min_child_weight=2, min_split_gain=0.9473684210526315, model_name='deal_model4', n_estimators=550, n_jobs=1, num_leaves=147, objective=None, output_dir='c:\\\\\\\\temp\\\\output', random_state=None, reg_alpha=0.7894736842105263, reg_lambda=0.05263157894736842, silent=True, subsample=0.1, subsample_for_bin=200000, subsample_freq=0, verbose=-10)"],"precision":[0.92136150234741787],"geometric mean":[0.77857408522092886],"recall":[0.950363196125908],"LIFT":[1.1917611826175609],"majority_obs":[1007],"f1":[0.93563766388557823],"minority obs":[3479]}}
```
### PipelineRun
<img width="1465" alt="image" src="https://user-images.githubusercontent.com/8158673/86960821-f3ae1400-c114-11ea-97a7-7902ecebf3e9.png">
### HyperDriveRun (Child of HyperDrive Step)
<img width="790" alt="image" src="https://user-images.githubusercontent.com/8158673/86960857-088aa780-c115-11ea-8ef3-6d56c8607f77.png">

**Comment by swatig007** [comment]
@nagau can you pls take a look?
@swanderz i see this issue is closed - does that mean it is resolved?

**Comment by swanderz** [comment]
It happened once. Issue went away when I re-ran. I created this issue in
case it happens again.
