### ISSUE TITLE
DataTransferSteps: `Failure in GetWorkspaceMsiToken while calling service AmlWorkspaceMsiToken`

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#1045]
Today our team couldn't run pipelines for hours due to "transient" Aether bugs. Eventually this went away, but it would be nice to have empathy for painful developer experiences, that these "transient" issues bring.

Our Pipeline has 82 steps, 22 of which are `DataTransferSteps`

#### Initially 1:23 AM PST
PipelineRun: `f36458bb-b0ae-433b-9f0a-bc7f3c73e28b`
DataTransferStep: `a986f46b-4194-47d6-8639-417ddff56d0d`
#### Again at 8:48  AM PST (with another pipeline entirely)
PipelineRun: `b42f91d0-9ce6-41d9-ab30-3b8a16538251`
DataTransferStep: `ce7eb22e-f5a2-4cb2-86a2-c13c3afbaee0`
### Exception and `executionlogs.txt`
```
Failure in GetWorkspaceMsiToken while calling service AmlWorkspaceMsiToken;
HttpMethod: GET; Response StatusCode: ;
Exception type: System.Net.Http.HttpRequestException|-System.Net.Sockets.SocketException and
stack trace:    at
Microsoft.Aether.BlueBox.S2S.Common.AmlWorkspaceMsiTokenProvider.GetWorkspaceMsiTokenAsync(WorkspaceIdentity workspaceIdentity, CreatedBy createdBy, String resourceName) in
d:\dbs\sh\Ae\0622_143416\cmd\5\src\aether\platform\backendV2\BlueBox\S2S.Common\Microsoft.Aether.BlueBox.S2S.Common\AmlWorkspaceMsiTokenProvider.cs:line 73
```

```
[2020-07-09 08:59:16Z] Parsing command text 
[2020-07-09 08:59:16Z] Parsed command line. Will be submitting job : {
  "Command": 2,
  "CopyCommand": null,
  "WaitCommand": null,
  "DataCopyCommand": {
    "ComputeName": "adf",
    "AzureDataFactoryConfig": null,
    "SourceDataId": "d0120be7-6de2-4e3f-b74c-2f98bd1b1d51",
    "DestinationDataId": "fb2a3884-f9da-4ed4-8409-169cc8c8e91a",
    "OutputDataId": "d64ce62b-944b-4b9f-bd73-2d37adac4568",
    "CopyOperationEntity": null,
    "CopyOptions": "{\"source_reference_type\": \"directory\", \"destination_reference_type\": \"directory\"}",
    "PolicyValidationStatus": 0
  },
  "IsDataManagementEnabled": true,
  "ComplianceCluster": null,
  "EuclidWorkspaceId": null
}
[2020-07-09 08:59:24Z] Data transfer job failed with unexpected error: Failure in GetWorkspaceMsiToken while calling service AmlWorkspaceMsiToken; HttpMethod: GET; Response StatusCode: ; Exception type: System.Net.Http.HttpRequestException|-System.Net.Sockets.SocketException and stack trace:    at Microsoft.Aether.BlueBox.S2S.Common.AmlWorkspaceMsiTokenProvider.GetWorkspaceMsiTokenAsync(WorkspaceIdentity workspaceIdentity, CreatedBy createdBy, String resourceName) in d:\dbs\sh\Ae\0622_143416\cmd\5\src\aether\platform\backendV2\BlueBox\S2S.Common\Microsoft.Aether.BlueBox.S2S.Common\AmlWorkspaceMsiTokenProvider.cs:line 73
   at Microsoft.Aether.BlueBox.S2S.Common.AmlWorkspaceMsiTokenProvider.GetWorkspaceMsiTokenAsync(WorkspaceIdentity workspaceIdentity, CreatedBy createdBy) in d:\dbs\sh\Ae\0622_143416\cmd\5\src\aether\platform\backendV2\BlueBox\S2S.Common\Microsoft.Aether.BlueBox.S2S.Common\AmlWorkspaceMsiTokenProvider.cs:line 43
   at Microsoft.Aether.DataTransferCloud.CopyService.DataFactoryCopyServiceFactory.CreateCopyServiceAsync(DataTransferJobMetadata job) in d:\dbs\sh\Ae\0625_091617\cmd\y\src\aether\platform\backendV2\BlueBox\Clouds\DataTransferCloudK8s\DataTransferCloudK8s.CopyService\DataFactoryCopyServiceFactory.cs:line 48
   at Microsoft.Aether.DataTransferCloud.JobProcessing.Actions.JobActionFactory.GetJobActionAsync(DataTransferJobMetadata job, StateMachine stateMachine) in d:\dbs\sh\Ae\0625_091617\cmd\n\src\aether\platform\backendV2\BlueBox\Clouds\DataTransferCloudK8s\DataTransferCloudK8s.JobProcessing\Actions\JobActionFactory.cs:line 41
   at Microsoft.Aether.DataTransferCloud.JobProcessing.DataCopyJobProcessor.ProcessJobAsync(DataTransferJobMetadata job) in d:\dbs\sh\Ae\0625_091617\cmd\n\src\aether\platform\backendV2\BlueBox\Clouds\DataTransferCloudK8s\DataTransferCloudK8s.JobProcessing\DataCopyJobProcessor.cs:line 44

```

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/8158673/87107342-6520bc00-c214-11ea-92f2-3f001451b3ca.png">

**Comment by swanderz** [comment]
From a support engineer:
> this issue was due to a Sev 2 incident caused by  a server in the pod having some issues (high memory consumption causing sporadic 500 failures). They have added retries in a specific failure condition in fetching the MSAI token to mitigate this going forward..
Closing this ticket now.
