### ISSUE TITLE
PythonScriptStep: Can't find Datastore's secret workspace's key vault

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#1046]
In a attempt to give ML Service a chance to perform without the experience of #1045, a dev on our team, simply resubmitted the pipeline.

Lo and behold, a new "transient" issue.

PipelineRun: `b4a84670-6f03-410f-97ed-74380aa1751c`
PythonScriptStep: `049bd22f-213d-432c-b4d8-c5ff2b4c3689`

### bug as exposed in UI
```json
UserError: Response status code does not indicate success: 404 (Datastore's secret is not found. Please make sure the workspace's key vault exists and the workspace).
{
  "error": {
    "code": "UserError",
    "severity": null,
    "message": "Datastore's secret is not found.
                Please make sure the workspace's key vault exists and
                the workspace have access to the secrets inside that key vault.",
    "messageFormat": null,
    "messageParameters": null,
    "referenceCode": null,
    "detailsUri": null,
    "target": null,
    "details": [],
    "innerError": {
      "code": "NotFoundError",
      "innerError": null
    },
    "debugInfo": null
  },
  "correlation": {
    "operation": "530b4d1121b4d647acca84ea8ec89fab",
    "request": "|530b4d1121b4d647acca84ea8ec89fab.f06627ab33bceb45."
  },
  "environment": "westus2",
  "location": "westus2",
  "time": "2020-07-09T11:52:22.4428907+00:00",
  "componentName": "data-store"
}
```

### `executionlogs.txt`

```python
[2020-07-09 11:51:59Z] Experiment: dealm-dealslipclf
[2020-07-09 11:51:59Z] Run Id:     049bd22f-213d-432c-b4d8-c5ff2b4c3689
[2020-07-09 11:51:59Z] Run target: dealm-dealslipcl
[2020-07-09 11:52:22Z] Failed to start the job because of error:
Failure in GetDataStoreDto while calling service DataStoreClient; HttpMethod: GET; Response StatusCode: NotFound;
Exception type:
Microsoft.RelInfra.Extensions.HttpRequestDetailException, stack trace:
   at Microsoft.Aether.BlueBox.DataStoreClient.DataStoreClient.GetAsync(String dataStoreName, WorkspaceIdentity workspaceIdentity, CreatedBy createdBy, CancellationToken cancellationToken) in d:\dbs\sh\Ae\0625_091617\cmd\4\src\aether\platform\backendV2\BlueBox\DataStoreClient\Microsoft.Aether.BlueBox.DataStoreClient\DataStoreClient.cs:line 107
   at Microsoft.Aether.BlueBox.Clouds.Common.OutputDataLocationUtils.GenerateOutputDataLocationAsync(AMLJobMetadata job, String outputName, String dataStoreName, IDataStoreClient dataStoreClient) in d:\dbs\sh\Ae\0625_091617\cmd\a\src\aether\platform\backendV2\BlueBox\Clouds\Clouds.Common\OutputDataLocationUtils.cs:line 123
   at Microsoft.Aether.BlueBox.Clouds.Common.OutputDataLocationUtils.GenerateOutputDataLocationAsync(AMLJobMetadata job, StructuredInterfaceOutput output, IDataStoreClient dataStoreClient) in d:\dbs\sh\Ae\0625_091617\cmd\a\src\aether\platform\backendV2\BlueBox\Clouds\Clouds.Common\OutputDataLocationUtils.cs:line 114
   at Microsoft.Aether.BlueBox.Clouds.Common.OutputDataLocationUtils.<>c__DisplayClass1_0.<<UpdateOutputDataLocationsAsync>b__3>d.MoveNext() in d:\dbs\sh\Ae\0625_091617\cmd\a\src\aether\platform\backendV2\BlueBox\Clouds\Clouds.Common\OutputDataLocationUtils.cs:line 53
   at Microsoft.RelInfra.Extensions.IEnumerableExtensions.<>c__DisplayClass1_1`1.<<ForEachAsync>b__1>d.MoveNext() in d:\dbs\sh\Ae\0622_130655\cmd\n\src\aether\platform\RelInfra\RelInfra.Common.Library\src\Extensions\IEnumerableExtensions.cs:line 27
   at Microsoft.Aether.BlueBox.Clouds.Common.OutputDataLocationUtils.UpdateOutputDataLocationsAsync(AMLJobMetadata job, IDataStoreClient dataStoreClient) in d:\dbs\sh\Ae\0625_091617\cmd\a\src\aether\platform\backendV2\BlueBox\Clouds\Clouds.Common\OutputDataLocationUtils.cs:line 46
   at Microsoft.Aether.EsCloud.Common.JobProcessor.StartRunAsync(EsCloudJobMetadata job) in d:\dbs\sh\Ae\0625_091617\cmd\t\src\aether\platform\backendV2\Clouds\ESCloud\ESCloudCommon\JobProcessor.cs:line 234

```

**Comment by swanderz** [comment]
FYI @jadhosn says his team also experienced this issue in the July 8-9 timeframe

**Comment by myshylin** [comment]
The underlying root cause is the same infrastructure problem in https://github.com/Azure/MachineLearningNotebooks/issues/1047
Should be recovered by now.

**Comment by swanderz** [comment]
ok great. I'll re-open if it happens again
