### ISSUE TITLE
DataTransferStep: Failed to get data factory config from compute target

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#1058]
file this under "transient" error. 2nd semi-persistent, transient issue we've seen with `DataTransferStep` in a week (see #1045 )

Created: `Jul 15, 2020 10:16 PM PST`
`DataTransferStep` id: `55478202-b1af-44ee-8197-89d3b201bd8d`
`PipelineRun` id: `9e754677-ac21-455c-a2b3-efa85ef8e9d2`

```python
[2020-07-16 05:16:29Z] Parsing command text 
[2020-07-16 05:16:29Z] Parsed command line. Will be submitting job : {
  "Command": 2,
  "CopyCommand": null,
  "WaitCommand": null,
  "DataCopyCommand": {
    "ComputeName": "adf",
    "AzureDataFactoryConfig": null,
    "SourceDataId": "16cad5a6-fccb-4ac7-9f94-6218dd1b9823",
    "DestinationDataId": "6f0cea65-9c72-46de-a9d3-1e54edb9ad4f",
    "OutputDataId": "05298bc7-997c-48ee-8517-b3bd74aab51b",
    "CopyOperationEntity": null,
    "CopyOptions": "{\"source_reference_type\": \"directory\", \"destination_reference_type\": \"directory\"}",
    "PolicyValidationStatus": 0
  },
  "IsDataManagementEnabled": true,
  "ComplianceCluster": null,
  "EuclidWorkspaceId": null
}
[2020-07-16 05:18:09Z] Data transfer job failed with unexpected error:
Failed to get data factory config from compute target and stack trace:
   at Microsoft.Aether.DataTransferCloud.CopyService.DataFactoryCopyServiceFactory.GetDataFactoryConfigFromComputeAsync(DataTransferJobMetadata job) in d:\dbs\sh\Ae\0710_161847\cmd\27\src\aether\platform\backendV2\BlueBox\Clouds\DataTransferCloudK8s\DataTransferCloudK8s.CopyService\DataFactoryCopyServiceFactory.cs:line 129
   at Microsoft.Aether.DataTransferCloud.CopyService.DataFactoryCopyServiceFactory.GetDataFactoryConfigAsync(DataTransferJobMetadata job) in d:\dbs\sh\Ae\0710_161847\cmd\27\src\aether\platform\backendV2\BlueBox\Clouds\DataTransferCloudK8s\DataTransferCloudK8s.CopyService\DataFactoryCopyServiceFactory.cs:line 76
   at Microsoft.Aether.DataTransferCloud.CopyService.DataFactoryCopyServiceFactory.CreateCopyServiceAsync(DataTransferJobMetadata job) in d:\dbs\sh\Ae\0710_161847\cmd\27\src\aether\platform\backendV2\BlueBox\Clouds\DataTransferCloudK8s\DataTransferCloudK8s.CopyService\DataFactoryCopyServiceFactory.cs:line 49
   at Microsoft.Aether.DataTransferCloud.JobProcessing.Actions.JobActionFactory.GetJobActionAsync(DataTransferJobMetadata job, StateMachine stateMachine) in d:\dbs\sh\Ae\0710_161847\cmd\i\src\aether\platform\backendV2\BlueBox\Clouds\DataTransferCloudK8s\DataTransferCloudK8s.JobProcessing\Actions\JobActionFactory.cs:line 41
   at Microsoft.Aether.DataTransferCloud.JobProcessing.DataCopyJobProcessor.ProcessJobAsync(DataTransferJobMetadata job) in d:\dbs\sh\Ae\0710_161847\cmd\i\src\aether\platform\backendV2\BlueBox\Clouds\DataTransferCloudK8s\DataTransferCloudK8s.JobProcessing\DataCopyJobProcessor.cs:line 44

```

**Comment by shbijlan** [comment]
@swanderz Thank you for your feedback. We are investigating each transient error independently. Let us know if this issue still persists.
