### ISSUE TITLE
CondaDependencies: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by jadhosn** [Azure/MachineLearningNotebooks#1061]
Currently running into this error `CondaDependencies` on SDK 1.9. Any idea what might be causing this? 

@CESARDELATORRE 

```python
dependencies = CondaDependencies.create(
    python_version='3.7',
    conda_packages=["python-dotenv"],
    pip_packages=["azureml-sdk==1.9", "pandas==1.0.5", "pygit2"],
    pin_sdk_version=False)
```
returns this error

>Traceback (most recent call last):
  File "C:/Users/sishakb/code/bc.model.appscore-frontline.api/main/pipeline.py", line 122, in <module>
    pin_sdk_version=False)
  File "C:\miniconda3\envs\appscore-frontline-api\lib\site-packages\azureml\core\conda_dependencies.py", line 198, in create
    cd.add_conda_package(conda_package)
  File "C:\miniconda3\envs\appscore-frontline-api\lib\site-packages\azureml\core\conda_dependencies.py", line 463, in add_conda_package
    self.set_python_version(python_version)
  File "C:\miniconda3\envs\appscore-frontline-api\lib\site-packages\azureml\core\conda_dependencies.py", line 420, in set_python_version
    self._conda_dependencies[PACKAGES][index] = PYTHON_PREFIX + '=' + version
TypeError: can only concatenate str (not "NoneType") to str
Process finished with exit code 1

**Comment by vizhur** [comment]
there is a known issue with conda packages that start with python. As a workaround please instantiate CondaDependencies object from yml file

```
name: mycondaenv
dependencies:
- python=3.7
- python-dotenv
- pip:
  - azureml-sdk==1.9
  - pandas==1.0.5
  - pygit2
```

CondaDependencies("myenv.yml")
or 
Environment.from_conda_specification("myenv", "myenv.yml")

Side note, please try to avoid meta-packages like azureml-sdk in your dependencies
