### ISSUE TITLE
Listing PipelineDrafts throw errors for pipeline created in the designer

### ISSUE THREAD

**Issue by ashic** [Azure/MachineLearningNotebooks#1092]
If I use 

```
PipelineDraft.list(workspace)
```
when there's a pipeline draft in the workspace that's been created in the designer, it fails with the following exception:

```
Traceback (most recent call last):
  File "../../ml/configure_ml.py", line 125, in <module>
    main()
  File "../../ml/configure_ml.py", line 118, in main
    pipelines.create_training_pipeline(ws)
  File "/mnt/e/dev/colibri/infrastructure/ml/helpers/pipelines.py", line 17, in create_training_pipeline
    existing = PipelineDraft.list(ws)
  File "/home/ashic/.conda/envs/colinfra/lib/python3.8/site-packages/azureml/pipeline/core/pipeline_draft.py", line 491, in list
    return graph_context.workflow_provider.pipeline_draft_provider.list_pipeline_drafts(workspace, tags=tags)
  File "/home/ashic/.conda/envs/colinfra/lib/python3.8/site-packages/azureml/pipeline/core/_aeva_provider.py", line 2579, in list_pipeline_drafts
    return [self.from_pipeline_draft_entity(
  File "/home/ashic/.conda/envs/colinfra/lib/python3.8/site-packages/azureml/pipeline/core/_aeva_provider.py", line 2579, in <listcomp>
    return [self.from_pipeline_draft_entity(
  File "/home/ashic/.conda/envs/colinfra/lib/python3.8/site-packages/azureml/pipeline/core/_aeva_provider.py", line 2500, in from_pipeline_draft_entity
    experiment_name=draft_entity.pipeline_submission_info.experiment_name,
AttributeError: 'NoneType' object has no attribute 'experiment_name'
```

The factory function seems to require an experiment name, but if you simply create a new pipeline in the designer, no experiment name is attached to it. During the list operation, the factory function is used that expects the experiment name, and this throws the exception. 

Is there any way to list pipeline drafts in a workspace when there's existing pipeline drafts that have been created in the designer?

**Comment by shbijlan** [comment]
@ashic Thank you for your feedback. We are investigating this issue and will update you shortly.

**Comment by shbijlan** [comment]
@ashic Thank you for bringing this bug to our attention. It has now been addressed and fixed by engineering. I am closing this issue. Please feel free to re-open if the issue persists.
