### ISSUE TITLE
Invalid int parameter seasonality: auto

### ISSUE THREAD

**Issue by pbartos** [Azure/MachineLearningNotebooks#1106]
AzureML Python SDK: 1.12.0

````
from azureml.pipeline.steps import AutoMLStep
from azureml.automl.core.forecasting_parameters import ForecastingParameters

forecasting_parameters = ForecastingParameters(
    time_column_name=time_column_name,
    forecast_horizon=forecast_horizon
)

automl_config = AutoMLConfig(task='forecasting',                             
                             training_data=train,
                             label_column_name=target_column_name,
                             compute_target=compute_target,
                             n_cross_validations=3,                             
                             verbosity=logging.INFO,
                             forecasting_parameters=forecasting_parameters)

trainWithAutomlStep = AutoMLStep(name="train",
                                    automl_config=automl_config)
````

**Error:**

[2020-08-18 10:30:05Z] Failed to start the job because of error: **Invalid int parameter seasonality: auto**, stack_trace:    at Microsoft.Aether.AutoMLCloud.Service.StructuredInterfaceParser.GetNullableInt(String jobId, Dictionary`2 parameters, String name) in d:\dbs\sh\Ae\0808_020019_1\cmd\22\src\aether\platform\backendV2\BlueBox\Clouds\AutoMLCloud\Service\StructuredInterfaceParser.cs:line 589
   at Microsoft.Aether.AutoMLCloud.Service.StructuredInterfaceParser.GetAutoMLSettings(Dictionary`2 parameterValues, AutoMLJobMetadata job) in d:\dbs\sh\Ae\0808_020019_1\cmd\22\src\aether\platform\backendV2\BlueBox\Clouds\AutoMLCloud\Service\StructuredInterfaceParser.cs:line 65
   at Microsoft.Aether.AutoMLCloud.Service.StructuredInterfaceParser.ParseStructuredInterface(AutoMLJobMetadata job) in d:\dbs\sh\Ae\0808_020019_1\cmd\22\src\aether\platform\backendV2\BlueBox\Clouds\AutoMLCloud\Service\StructuredInterfaceParser.cs:line 30
   at Microsoft.Aether.AutoMLCloud.Service.JobProcessor.InitializeNewJob(AutoMLJobMetadata job) in d:\dbs\sh\Ae\0808_020019_1\cmd\22\src\aether\platform\backendV2\BlueBox\Clouds\AutoMLCloud\Service\JobProcessor.cs:line 232
   at Microsoft.Aether.AutoMLCloud.Service.JobProcessor.StartNewJobAsync(AutoMLJobMetadata job) in d:\dbs\sh\Ae\0808_020019_1\cmd\22\src\aether\platform\backendV2\BlueBox\Clouds\AutoMLCloud\Service\JobProcessor.cs:line 161

**Comment by rtanase** [comment]
@jialiu103 can you please have a look here? The forecasting parameters might have introduced a breaking change in the contract, wrt datatype of seasonality parameter.

**Comment by jialiu103** [comment]
Absolutely. @pbartos this is an known issue and the fix is ready to be deployed to prod regions. It might take 1-2 weeks to reach all the regions.

**Comment by swatig007** [comment]
@jialiu103 @cartacioS , can you pls see if the fix is already deployed, and update this issue accprdingly

**Comment by pbartos** [comment]
It's working now on version 1.13.0. Closing.
