### ISSUE TITLE
Ml pipeline failed - AutoMLStep 

### ISSUE THREAD

**Issue by josesriver** [Azure/MachineLearningNotebooks#1194]
Hi,

I am running a 5-step pipeline. The third step is an AutoMLStep. This step trains a regression task and when it seems that all iterations are completed, the pipeline fails and the remaining steps are not executed.

The execution log is the following:

...
[2020-10-19 12:30:24Z] Job is running, job runstatus is Running
[2020-10-19 12:30:39Z] Job is running, job runstatus is Running
[2020-10-19 12:30:57Z] Job is running, job runstatus is Running
[2020-10-19 12:31:14Z] Job is running, job runstatus is Running
[2020-10-19 12:31:26Z] Job finished, job RunId is c0755db9-249f-4309-a706-0dbae092b2b9
[2020-10-19 12:32:08Z] Failed to update outputs and mark job as failed. Exception_type: ServiceInvocationException, error: Failure in GetRunMetrics while calling service RunHistory; HttpMethod: GET; Response StatusCode: BadRequest; Exception type: Microsoft.RelInfra.Extensions.HttpRequestDetailException, stack_trace:    at Microsoft.Aether.BlueBox.RunHistoryClient.RunHistoryClient.<>c__DisplayClass43_0.<<GetRunMetrics>g__getter|1>d.MoveNext() in d:\dbs\sh\Ae\1009_020029\cmd\k\src\aether\platform\backendV2\BlueBox\RunHistoryClient\src\client\RunHistoryClient.cs:line 732
   at Microsoft.Aether.BlueBox.RunHistoryClient.PaginatedResultHelper.GetAggregateResultAsync[T](Func`2 getter, QueryParamsDto queryParams)
   at Microsoft.Aether.BlueBox.RunHistoryClient.RunHistoryClient.GetRunMetrics(WorkspaceIdentity amlWorkspaceIdentity, String experimentName, IEnumerable`1 runs, CreatedBy createdBy) in d:\dbs\sh\Ae\1009_020029\cmd\k\src\aether\platform\backendV2\BlueBox\RunHistoryClient\src\client\RunHistoryClient.cs:line 736
   at Microsoft.Aether.BlueBox.RunHistoryClient.RunHistoryClient.GetBatchRunMetrics(WorkspaceIdentity amlWorkspaceIdentity, String experimentName, IEnumerable`1 runs, Int32 batchSize, CreatedBy createdBy) in d:\dbs\sh\Ae\1009_020029\cmd\k\src\aether\platform\backendV2\BlueBox\RunHistoryClient\src\client\RunHistoryClient.cs:line 679
   at Microsoft.Aether.BlueBox.RunHistoryClient.RunHistoryClient.GetRunMetricsForChildrenAsync(WorkspaceIdentity amlWorkspaceIdentity, String experimentName, String parentRunId, CreatedBy createdBy) in d:\dbs\sh\Ae\1009_020029\cmd\k\src\aether\platform\backendV2\BlueBox\RunHistoryClient\src\client\RunHistoryClient.cs:line 538
   at Microsoft.Aether.BlueBox.Clouds.Common.RunMetricsHelper.GetAllChildRunMetricsByRunIdAsync(WorkspaceIdentity workspaceIdentity, String experimentName, String parentRunId, IRunHistoryClient runHistoryClient, CreatedBy createdBy) in d:\dbs\sh\Ae\1009_020029\cmd\1v\src\aether\platform\backendV2\BlueBox\Clouds\Clouds.Common\RunMetricsHelper.cs:line 27
   at Microsoft.Aether.BlueBox.Clouds.Common.RunMetricsHelper.GetSerializedChildRunMetricsOutputAsync(WorkspaceIdentity workspaceIdentity, String experimentName, String parentRunId, IRunHistoryClient runHistoryClient, CreatedBy createdBy) in d:\dbs\sh\Ae\1009_020029\cmd\1v\src\aether\platform\backendV2\BlueBox\Clouds\Clouds.Common\RunMetricsHelper.cs:line 19
   at Microsoft.Aether.AutoMLCloud.Service.JobProcessor.UpdateOutputsAsync(AutoMLJobMetadata job) in d:\dbs\sh\Ae\1009_020029\cmd\29\src\aether\platform\backendV2\BlueBox\Clouds\AutoMLCloud\Service\JobProcessor.cs:line 610
   at Microsoft.Aether.AutoMLCloud.Service.JobProcessor.CheckRunStatusAsync(AutoMLJobMetadata job, RunDto runDto) in d:\dbs\sh\Ae\1009_020029\cmd\29\src\aether\platform\backendV2\BlueBox\Clouds\AutoMLCloud\Service\JobProcessor.cs:line 452

The configuration of the step:

automl_settings = {
    "iteration_timeout_minutes" : 5,
    "iterations" : 100, 
    "experiment_timeout_hours" : 3, 
    "max_concurrent_iterations" : 4,
    "n_cross_validations" : 5,
    "primary_metric" : 'normalized_root_mean_squared_error',
    "model_explainability" : True
}

automl_config = AutoMLConfig(name='AutoML task',
                             task = 'regression',
                             debug_log = 'automated_ml_errors.log',
                             compute_target = aml_cluster,
                             run_configuration = automl_run_config,
                             featurization = 'auto',
                             training_data = prepared_data,
                             path = './automated_ml',
                             label_column_name = 'label',
                             **automl_settings)

train_step = AutoMLStep(name='AutoML',
                        automl_config=automl_config,outputs=[metrics_data,model_data],
                        allow_reuse=True)
						
I have to say that when I set the number of iterations (iterations in automl_settings) with a smaller number (say 5 or 10), everything goes ok.

Thank you in advance!

**Comment by CESARDELATORRE** [comment]
Adding some folks from the team: @rtanase, @anupaaggarwal, @swatig007 to follow up on this issue.

**Comment by swatig007** [comment]
@sonnypark this failure is coming from Pipelines service. Do you know who from Pipelines team can take a look?

**Comment by sonnypark** [comment]
This is known issue which we are currently deploying the fix.

**Comment by josesriver** [comment]
Thank you all!! @sonnypark, do you have an estimate of when it will be ready?

**Comment by sonnypark** [comment]
It has been deployed to all prod!

**Comment by josesriver** [comment]
Perfect! Thank you! Then I close the issue.
