### ISSUE TITLE
ModuleNotFoundError in Conda Env created by AzureML

### ISSUE THREAD

**Issue by nihil0** [Azure/MachineLearningNotebooks#123]
I am trying to develop some code to locally test by `score.py` script. 

I first created a conda environment by running `conda env create -f mydeployenv.yml` which was created by the code in [this](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/azure-databricks/04.Deploy_to_ACI.ipynb) notebook. I then activate this environment and start a python shell in it. 

The first line in my `score.py` is `from azureml.core.model import Model`. I get the following error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\project_environment\lib\site-packages\azureml\core\__init__.py", line 6, in <module>
    from azureml.core.workspace import Workspace
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\project_environment\lib\site-packages\azureml\core\workspace.py", line 24, in <module>
    from azureml._project import _commands
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\project_environment\lib\site-packages\azureml\_project\_commands.py", line 19, in <module>
    from azureml._workspace._utils import (
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\project_environment\lib\site-packages\azureml\_workspace\_utils.py", line 14, in <module>
    from azure.cli.core.cloud import get_active_cloud
ModuleNotFoundError: No module named 'azure.cli.core'
```

Why am I getting this error, and how do I go about testing the `score.py` script from withing the conda env?

**Comment by adyada** [comment]
Can you please post contents of mydeployenv.yml? 
It looks like project_environment conda environment is not isolated. 

One way to check that is:

1) conda create -n mynewenv python=3.6.2
2) activate mynewenv
3) pip freeze

In pip freeze, you should not see many packages. If you are seeing a lot of packages specially azure packages then that means that mynewenv conda environment is not isolated, i.e., it is inheriting packages from outside that environment that you didn't even install.  You can work around this by specifying a different python version like 3.6.5 or something else.
