### ISSUE TITLE
Import OpenSSL raising AttributeError: module 'lib' has no attribute 'Cryptography_HAS_TLSEXT_HOSTNAME' 

### ISSUE THREAD

**Issue by weiyx16** [Azure/MachineLearningNotebooks#1259]
Hello! 
Recently, I want to submit a job to k8s (aka ITP) platform and run a distributed pytorch training script, but unfortunately, before executing my own script, something raises errors when preparing the job. I think it's caused by the conflict between `PyOpenSSL` and newest version of `cryptography`. And this issue has been mentioned in #https://github.com/pyca/pyopenssl/issues/973
Not sure the best solution for this problem.
Thanks for all your help! and the following is the traceback:
```
2020-12-09 15:46:49 Process Process-1:
2020-12-09 15:46:49 Traceback (most recent call last):
2020-12-09 15:46:49   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
2020-12-09 15:46:49     self.run()
2020-12-09 15:46:49   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
2020-12-09 15:46:49     self._target(*self._args, **self._kwargs)
2020-12-09 15:46:49   File "/job-prep-scripts/******/job_prep.py", line 170, in downloadDataStore
2020-12-09 15:46:49     datastore_context_manager = get_datastore_context_manager(options)
2020-12-09 15:46:49   File "/job-prep-scripts/******/azureml_globals.py", line 88, in get_datastore_context_manager
2020-12-09 15:46:49     from context_manager_injector import create_wrapped_context_manager
2020-12-09 15:46:49   File "/job-prep-scripts/******/context_manager_injector.py", line 37, in <module>
2020-12-09 15:46:49     from azureml.exceptions import AzureMLException
2020-12-09 15:46:49   File "/opt/conda/lib/python3.6/site-packages/azureml/exceptions/__init__.py", line 24, in <module>
2020-12-09 15:46:49     from azureml._restclient.exceptions import ServiceException
2020-12-09 15:46:49   File "/opt/conda/lib/python3.6/site-packages/azureml/_restclient/__init__.py", line 7, in <module>
2020-12-09 15:46:49     from .rest_client import RestClient
2020-12-09 15:46:49   File "/opt/conda/lib/python3.6/site-packages/azureml/_restclient/rest_client.py", line 12, in <module>
2020-12-09 15:46:49     from msrest.service_client import ServiceClient
2020-12-09 15:46:49   File "/opt/conda/lib/python3.6/site-packages/msrest/__init__.py", line 28, in <module>
2020-12-09 15:46:49     from .configuration import Configuration
2020-12-09 15:46:49   File "/opt/conda/lib/python3.6/site-packages/msrest/configuration.py", line 37, in <module>
2020-12-09 15:46:49     from .pipeline import Pipeline
2020-12-09 15:46:49   File "/opt/conda/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 52, in <module>
2020-12-09 15:46:49     from requests.structures import CaseInsensitiveDict
2020-12-09 15:46:49   File "/opt/conda/lib/python3.6/site-packages/requests/__init__.py", line 95, in <module>
2020-12-09 15:46:49     from urllib3.contrib import pyopenssl
2020-12-09 15:46:49   File "/opt/conda/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
2020-12-09 15:46:49     import OpenSSL.SSL
2020-12-09 15:46:49   File "/opt/conda/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
2020-12-09 15:46:49     from OpenSSL import crypto, SSL
2020-12-09 15:46:49   File "/opt/conda/lib/python3.6/site-packages/OpenSSL/SSL.py", line 673, in <module>
2020-12-09 15:46:49     _lib.Cryptography_HAS_TLSEXT_HOSTNAME, "SNI not available"
2020-12-09 15:46:49 AttributeError: module 'lib' has no attribute 'Cryptography_HAS_TLSEXT_HOSTNAME'
```

**Comment by vizhur** [comment]
you control all the dependencies for your job environment, you can upperbound cryptography dependency to unblock yourself

**Comment by weiyx16** [comment]
Thank you for your warm help. I solved by controlling the `cryptography` version myself.
