### ISSUE TITLE
AutoMLStep returns Parameter Script not found error

### ISSUE THREAD

**Issue by pbartos** [Azure/MachineLearningNotebooks#1261]
SDK version: 1.19.0

**Example notebook:**
[Azure Machine Learning Pipeline with AutoMLStep](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-with-automated-machine-learning-step.ipynb)

**Error**:
``[2020-12-11 12:10:07Z] Failed to start the job because of error: Parameter Script not found, error_type: ArgumentException, stack_trace:    at Microsoft.Aether.AutoMLCloud.Service.StructuredInterfaceParser.GetParameterValue(String jobId, Dictionary`2 parameters, String name) in d:\dbs\sh\Ae\1123_122335\cmd\s\src\aether\platform\backendV2\BlueBox\Clouds\AutoMLCloud\Service\StructuredInterfaceParser.cs:line 644
   at Microsoft.Aether.AutoMLCloud.Service.StructuredInterfaceParser.GetRunConfiguration(String jobId, Dictionary`2 parameters, List`1 arguments) in d:\dbs\sh\Ae\1123_122335\cmd\s\src\aether\platform\backendV2\BlueBox\Clouds\AutoMLCloud\Service\StructuredInterfaceParser.cs:line 160
   at Microsoft.Aether.AutoMLCloud.Service.StructuredInterfaceParser.GetRunDefinition(Dictionary`2 parameterValues, AutoMLJobMetadata job) in d:\dbs\sh\Ae\1123_122335\cmd\s\src\aether\platform\backendV2\BlueBox\Clouds\AutoMLCloud\Service\StructuredInterfaceParser.cs:line 64
   at Microsoft.Aether.AutoMLCloud.Service.StructuredInterfaceParser.ParseStructuredInterface(AutoMLJobMetadata job) in d:\dbs\sh\Ae\1123_122335\cmd\s\src\aether\platform\backendV2\BlueBox\Clouds\AutoMLCloud\Service\StructuredInterfaceParser.cs:line 25
   at Microsoft.Aether.AutoMLCloud.Service.JobProcessor.InitializeNewJob(AutoMLJobMetadata job) in d:\dbs\sh\Ae\1123_122335\cmd\s\src\aether\platform\backendV2\BlueBox\Clouds\AutoMLCloud\Service\JobProcessor.cs:line 242
   at Microsoft.Aether.AutoMLCloud.Service.JobProcessor.StartNewJobAsync(AutoMLJobMetadata job) in d:\dbs\sh\Ae\1123_122335\cmd\s\src\aether\platform\backendV2\BlueBox\Clouds\AutoMLCloud\Service\JobProcessor.cs:line 170
``

**Comment by Aniththa** [comment]
Hi @pbartos! Thanks for reaching out. This was a known issue that has been fixed in all regions as of 12/11. Please rerun your pipeline and this should fix this issue. Feel free to reach out if you have any other questions.

**Comment by pbartos** [comment]
It's working now. Thanks.
