### ISSUE TITLE
ERROR:  Learning: Build AI solutions with Azure Machine Learning - 06 - Work with Data - Upload data to a datastore

### ISSUE THREAD

**Issue by jb80016** [Azure/MachineLearningNotebooks#1348]
**Upload data to a datastore**
![AzureUpload](https://user-images.githubusercontent.com/947785/108407641-3e325b80-71e1-11eb-85df-58479ed8db52.png)

Now that you have determined the available datastores, you can upload files from your local file system to a datastore so that it will be accessible to experiments running in the workspace, regardless of where the experiment script is actually being run.

_default_ds.upload_files(files=['./data/diabetes.csv', './data/diabetes2.csv'], # Upload the diabetes csv files in /data
                       target_path='diabetes-data/', # Put it in a folder path in the datastore
                       overwrite=True, # Replace existing files of the same name
                       show_progress=True)_

Uploading an estimated of 2 files
Uploading ./data/diabetes.csv
Uploading ./data/diabetes2.csv
Uploaded 0 files
--- Logging error ---
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/data/azure_storage_datastore.py", line 332, in handler
    result = future.result()
  File "/anaconda/envs/azureml_py36/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/anaconda/envs/azureml_py36/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/anaconda/envs/azureml_py36/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/data/azure_storage_datastore.py", line 787, in <lambda>
    lambda target, source: lambda: self.blob_service.create_blob_from_path(self.container_name, target, source)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_vendor/azure_storage/blob/blockblobservice.py", line 463, in create_blob_from_path
    timeout=timeout)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_vendor/azure_storage/blob/blockblobservice.py", line 582, in create_blob_from_stream
    timeout=timeout)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_vendor/azure_storage/blob/blockblobservice.py", line 971, in _put_blob
    return self._perform_request(request, _parse_base_properties)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_vendor/azure_storage/common/storageclient.py", line 381, in _perform_request
    raise ex
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_vendor/azure_storage/common/storageclient.py", line 306, in _perform_request
    raise ex
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_vendor/azure_storage/common/storageclient.py", line 292, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_vendor/azure_storage/common/_error.py", line 115, in _http_error_handler
    raise ex
azure.common.AzureHttpError: This request is not authorized to perform this operation using this permission. ErrorCode: AuthorizationPermissionMismatch
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
RequestId:a9ffd72c-c01e-00d9-5220-064b2e000000
Time:2021-02-18T18:02:54.3372191Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/envs/azureml_py36/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/anaconda/envs/azureml_py36/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/anaconda/envs/azureml_py36/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/anaconda/envs/azureml_py36/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/anaconda/envs/azureml_py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda/envs/azureml_py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 612, in start
    self.io_loop.start()
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/anaconda/envs/azureml_py36/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
    self._run_once()
  File "/anaconda/envs/azureml_py36/lib/python3.6/asyncio/base_events.py", line 1451, in _run_once
    handle._run()
  File "/anaconda/envs/azureml_py36/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/tornado/ioloop.py", line 688, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/tornado/gen.py", line 814, in inner
    self.ctx_run(self.run)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/tornado/gen.py", line 775, in run
    yielded = self.gen.send(value)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 362, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 302, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 539, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2867, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2895, in _run_cell
    return runner(coro)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3072, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3263, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-30-0f28dc9194af>", line 4, in <module>
    show_progress=True)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/data/azure_storage_datastore.py", line 787, in upload_files
    lambda target, source: lambda: self.blob_service.create_blob_from_path(self.container_name, target, source)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/data/azure_storage_datastore.py", line 321, in _start_upload_task
    tq.add_task(async_task)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_common/async_utils/task_queue.py", line 55, in __exit__
    self.flush(self.identity)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_common/async_utils/task_queue.py", line 118, in flush
    self._results.extend((task.wait(awaiter_name=self.identity) for task in completed_tasks))
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_common/async_utils/task_queue.py", line 118, in <genexpr>
    self._results.extend((task.wait(awaiter_name=self.identity) for task in completed_tasks))
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_common/async_utils/async_task.py", line 58, in wait
    res = self._handler(self._future, self._logger)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/data/azure_storage_datastore.py", line 340, in handler
    exception_handler(e, logger)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/data/azure_storage_datastore.py", line 304, in exception_handler
    logger.error("Upload failed, please make sure target_path does not start with invalid characters.", e)
Message: 'Upload failed, please make sure target_path does not start with invalid characters.'
Arguments: (AzureHttpError('This request is not authorized to perform this operation using this permission. ErrorCode: AuthorizationPermissionMismatch\n<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.\nRequestId:a9ffd72c-c01e-00d9-5220-064b2e000000\nTime:2021-02-18T18:02:54.3372191Z</Message></Error>',),)
--- Logging error ---
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/data/azure_storage_datastore.py", line 332, in handler
    result = future.result()
  File "/anaconda/envs/azureml_py36/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/anaconda/envs/azureml_py36/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/anaconda/envs/azureml_py36/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/data/azure_storage_datastore.py", line 787, in <lambda>
    lambda target, source: lambda: self.blob_service.create_blob_from_path(self.container_name, target, source)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_vendor/azure_storage/blob/blockblobservice.py", line 463, in create_blob_from_path
    timeout=timeout)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_vendor/azure_storage/blob/blockblobservice.py", line 582, in create_blob_from_stream
    timeout=timeout)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_vendor/azure_storage/blob/blockblobservice.py", line 971, in _put_blob
    return self._perform_request(request, _parse_base_properties)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_vendor/azure_storage/common/storageclient.py", line 381, in _perform_request
    raise ex
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_vendor/azure_storage/common/storageclient.py", line 306, in _perform_request
    raise ex
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_vendor/azure_storage/common/storageclient.py", line 292, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_vendor/azure_storage/common/_error.py", line 115, in _http_error_handler
    raise ex
azure.common.AzureHttpError: This request is not authorized to perform this operation using this permission. ErrorCode: AuthorizationPermissionMismatch
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
RequestId:5488fc90-001e-0080-5d20-064ea8000000
Time:2021-02-18T18:02:54.3372332Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/envs/azureml_py36/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/anaconda/envs/azureml_py36/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/anaconda/envs/azureml_py36/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/anaconda/envs/azureml_py36/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/anaconda/envs/azureml_py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda/envs/azureml_py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 612, in start
    self.io_loop.start()
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/anaconda/envs/azureml_py36/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
    self._run_once()
  File "/anaconda/envs/azureml_py36/lib/python3.6/asyncio/base_events.py", line 1451, in _run_once
    handle._run()
  File "/anaconda/envs/azureml_py36/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/tornado/ioloop.py", line 688, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/tornado/gen.py", line 814, in inner
    self.ctx_run(self.run)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/tornado/gen.py", line 775, in run
    yielded = self.gen.send(value)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 362, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 302, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 539, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2867, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2895, in _run_cell
    return runner(coro)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3072, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3263, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-30-0f28dc9194af>", line 4, in <module>
    show_progress=True)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/data/azure_storage_datastore.py", line 787, in upload_files
    lambda target, source: lambda: self.blob_service.create_blob_from_path(self.container_name, target, source)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/data/azure_storage_datastore.py", line 321, in _start_upload_task
    tq.add_task(async_task)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_common/async_utils/task_queue.py", line 55, in __exit__
    self.flush(self.identity)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_common/async_utils/task_queue.py", line 118, in flush
    self._results.extend((task.wait(awaiter_name=self.identity) for task in completed_tasks))
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_common/async_utils/task_queue.py", line 118, in <genexpr>
    self._results.extend((task.wait(awaiter_name=self.identity) for task in completed_tasks))
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_common/async_utils/async_task.py", line 58, in wait
    res = self._handler(self._future, self._logger)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/data/azure_storage_datastore.py", line 340, in handler
    exception_handler(e, logger)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/data/azure_storage_datastore.py", line 304, in exception_handler
    logger.error("Upload failed, please make sure target_path does not start with invalid characters.", e)
Message: 'Upload failed, please make sure target_path does not start with invalid characters.'
Arguments: (AzureHttpError('This request is not authorized to perform this operation using this permission. ErrorCode: AuthorizationPermissionMismatch\n<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.\nRequestId:5488fc90-001e-0080-5d20-064ea8000000\nTime:2021-02-18T18:02:54.3372332Z</Message></Error>',),)
$AZUREML_DATAREFERENCE_010e49b94ea645928f99f4a15d7b3a00
from azurem

**Comment by lostmygithubaccount** [comment]
@jb80016 can you provide more context on this issue? which example are you using? is it from this repository or elsewhere?

**Comment by jb80016** [comment]
LEARNING PATH
Build AI solutions with Azure Machine Learning
Work with Data in Azure Machine Learning  link:  https://docs.microsoft.com/en-us/learn/modules/work-with-data-in-aml/ 
Cloned this repository to workspace within Azure using public key:  git@github.com:MicrosoftLearning/mslearn-dp100.git 

Let me know if any other info would be helpful.

**Comment by jb80016** [comment]
I figured it out using:  

from azureml.core import Workspace
ws = Workspace.from_config()
datastore = ws.get_default_datastore()
datastore.upload(src_dir='./data',
                 target_path='diabetes-data',
                 overwrite=True)

from azureml.core import Dataset

# Get the default datastore
default_ds = ws.get_default_datastore()

#Create a tabular dataset from the path on the datastore (this may take a short while)
tab_data_set = Dataset.Tabular.from_delimited_files(path=(default_ds, 'diabetes-data/*.csv'))

# Display the first 20 rows as a Pandas dataframe
tab_data_set.take(20).to_pandas_dataframe()

**Comment by SturgeonMi** [comment]
We are closing this issue, but if you have any follow-ups, please reopen it!  #please-close
