### ISSUE TITLE
Failed to add item to collection: PipelineEndpoint (conflict error)

### ISSUE THREAD

**Issue by JackCaster** [Azure/MachineLearningNotebooks#1515]
I am having troubles working with `PipelineEndpoint`.

I built a pipeline and publish it:
```python
published_pipeline = pipeline.publish(
        name=...,
        description=...,
    )
```
then I create an endpoint and add the newly created pipeline:
```python
pipeline_endpoint = PipelineEndpoint.publish(
            workspace=ws,
            name=...,
            pipeline=published_pipeline,
            description=...,
        )
```
but got a "conflict" error, which is a bit obscure to me:
```python
azureml.pipeline.core._restclients.aeva.models.error_response.ErrorResponseException: (UserError) Response status code does not indicate success: 409 (Conflict).
Microsoft.RelInfra.Common.Exceptions.ErrorResponseException: Failed to add item to collection: PipelineEndpoint, id: 9dcbeb92-8bd8-4f50-81f2-cc5c7b4d627b, partition: 671e84b0-a21e-49e2-a749-e1fdd25314e3, error code: Conflict
```
I thought the problem could arise because there was another pipeline endpoint with the same name. I checked with `PipelineEndpoint.list(ws, active_only=True)` and there is not (there are some endpoints with the same name from older attempts but they are disabled)

Full traceback:
```python
Traceback (most recent call last):
  File "C:\dev\miniconda\envs\xxx\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\dev\miniconda\envs\xxx\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\yyy\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\yyy\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\yyy\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\dev\miniconda\envs\xxx\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\dev\miniconda\envs\xxx\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\dev\miniconda\envs\xxx\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\dev\xxx\pipeline_inference.py", line 309, in <module>
    main(args)
  File "c:\dev\xxx\pipeline_inference.py", line 191, in main
    description="description",
  File "C:\dev\miniconda\envs\xxx\lib\site-packages\azureml\pipeline\core\pipeline_endpoint.py", line 319, in publish
    pipeline_endpoint = pipeline_endpoint_provider.create_pipeline_endpoint(name, description, pipeline_id)
  File "C:\dev\miniconda\envs\xxx\lib\site-packages\azureml\pipeline\core\_aeva_provider.py", line 2107, in create_pipeline_endpoint
    pipeline_endpoint_entity = self._service_caller.create_pipeline_endpoint_async(pipeline_endpoint_creation_info)
  File "C:\dev\miniconda\envs\xxx\lib\site-packages\azureml\pipeline\core\_restclients\aeva\service_caller.py", line 740, in create_pipeline_endpoint_async
    pipeline_endpoint_creation_info=pipeline_endpoint_creation_info)
  File "C:\dev\miniconda\envs\xxx\lib\site-packages\azureml\pipeline\core\_restclients\aeva\aml_pipelines_api10.py", line 4442, in api_v10_subscriptions_by_subscription_id_resource_groups_by_resource_group_name_providers_microsoft_machine_learning_services_workspaces_by_workspace_name_pipeline_endpoint_create_post
    raise ErrorResponseException(self._deserialize, response)
azureml.pipeline.core._restclients.aeva.models.error_response.ErrorResponseException: (UserError) Response status code does not indicate success: 409 (Conflict).
Microsoft.RelInfra.Common.Exceptions.ErrorResponseException: Failed to add item to collection: PipelineEndpoint, id: 9dcbeb92-8bd8-4f50-81f2-cc5c7b4d627b, partition: 671e84b0-a21e-49e2-a749-e1fdd25314e3, error code: Conflict
```
Would you be able to help? I would not know where to start debugging this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f506755-3573-985e-46e4-0554b8652214
* Version Independent ID: 340f468f-ae38-70f8-267f-abbc7294ccdd
* Content: [azureml.pipeline.core.pipeline_endpoint.PipelineEndpoint class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipeline_endpoint.pipelineendpoint?view=azure-ml-py#publish-workspace--name--description--pipeline---workflow-provider-none---service-endpoint-none-)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.pipeline_endpoint.PipelineEndpoint.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.pipeline_endpoint.PipelineEndpoint.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by JackCaster** [comment]
I was made aware that the error is triggered when an endpoint with the same name exists---regardless of whether it is disabled or not. The way to reuse a pipeline endpoint is to 
```python
endpoint_name = 'your_name'
endpoints_available = PipelineEndpoint.list(ws, active_only=False)
for i in endpoints_available:
        if i.name == endpoint_name:
            i.disable()
            i.archive()
```
Perhaps we could clarify this in the doc?
