### ISSUE TITLE
`submit` with `pipeline_parameters` does not work as described

### ISSUE THREAD

**Issue by stoney95** [Azure/MachineLearningNotebooks#1606]
```python
pipeline_run = experiment.submit(pipeline, pipeline_parameters={"input_data": new_data_path})
```

From the docu you should be able to set pipeline parameters on pipeline submit. This didn't work for me.

```shell
>>> python create_pipeline.py
Traceback (most recent call last):
  File "create_pipeline.py", line 172, in <module>
    main()
  File "create_pipeline.py", line 57, in main
    experiment.submit(pipeline, pipeline_parameters={"automl_iterations", 2})
  File "/Users/simons/anaconda3/envs/ai_attack/lib/python3.6/site-packages/azureml/core/experiment.py", line 220, in submit
    run = submit_func(config, self.workspace, self.name, **kwargs)
  File "/Users/simons/anaconda3/envs/ai_attack/lib/python3.6/site-packages/azureml/pipeline/core/pipeline.py", line 51, in _submit_pipeline
    enable_email_notification=enable_email_notification)
  File "/Users/simons/anaconda3/envs/ai_attack/lib/python3.6/site-packages/azureml/pipeline/core/pipeline.py", line 281, in submit
    enable_email_notification=enable_email_notification)
  File "/Users/simons/anaconda3/envs/ai_attack/lib/python3.6/site-packages/azureml/pipeline/core/graph.py", line 3771, in submit
    self._validate_and_finalize(pipeline_parameters=pipeline_parameters, regenerate_outputs=regenerate_outputs)
  File "/Users/simons/anaconda3/envs/ai_attack/lib/python3.6/site-packages/azureml/pipeline/core/graph.py", line 3849, in _validate_and_finalize
    self._validate_pipeline_params(pipeline_parameters)
  File "/Users/simons/anaconda3/envs/ai_attack/lib/python3.6/site-packages/azureml/pipeline/core/graph.py", line 3731, in _validate_pipeline_params
    for key, value in pipeline_params.items():
AttributeError: 'set' object has no attribute 'items'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f44644d4-e8d2-1a82-1858-95abb5e4294c
* Version Independent ID: 2b538246-2460-1536-4e6c-ac77a25c67d6
* Content: [azureml.pipeline.core.PipelineParameter class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipelineparameter?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.PipelineParameter.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.PipelineParameter.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by stoney95** [comment]
Error was on my side, unfortunately submitted with `{"automl_iterations", 2}`. Will close this now.
