### ISSUE TITLE
ParallelRunStep on Intermediate Partitioned File Dataset Failing

### ISSUE THREAD

**Issue by jtisbell4** [Azure/MachineLearningNotebooks#1648]
Hi,

I am attempting to use `ParallelRunStep` for a batch training job. The data that is being ingested for training is a partitioned file dataset, so I am using [this example notebook](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/parallel-run/file-dataset-partition-per-folder.ipynb) as a template. 

In my script, the batch training step is preceded by a data pulling step, so the `input` to the training step is of type `OutputDatasetConfig` rather than `Dataset.File.from_files`, which is how it is done in the example notebook. Because of this, the training step fails with the following error:

azureml_common.parallel_run.exception_info.Exception: Run failed. Below is the error detail:
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/sdpesp-dev-cvx/azureml/7d68a66e-aa64-4732-a159-22d477774715/wd/azureml/7d68a66e-aa64-4732-a159-22d477774715/driver/simulator.py", line 93, in main
    simulator.wait()
  File "/mnt/batch/tasks/shared/LS_root/jobs/sdpesp-dev-cvx/azureml/7d68a66e-aa64-4732-a159-22d477774715/wd/7d68a66e-aa64-4732-a159-22d477774715/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/masterless_simulator.py", line 122, in wait
    ProgressReport().save()
  File "/mnt/batch/tasks/shared/LS_root/jobs/sdpesp-dev-cvx/azureml/7d68a66e-aa64-4732-a159-22d477774715/wd/7d68a66e-aa64-4732-a159-22d477774715/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/progress_report.py", line 191, in save
    task_exporter.save()
  File "/mnt/batch/tasks/shared/LS_root/jobs/sdpesp-dev-cvx/azureml/7d68a66e-aa64-4732-a159-22d477774715/wd/7d68a66e-aa64-4732-a159-22d477774715/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_exporter.py", line 113, in save
    self.save_remaining()
  File "/mnt/batch/tasks/shared/LS_root/jobs/sdpesp-dev-cvx/azureml/7d68a66e-aa64-4732-a159-22d477774715/wd/7d68a66e-aa64-4732-a159-22d477774715/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_exporter.py", line 100, in save_remaining
    for task in total_tasks:
  File "/mnt/batch/tasks/shared/LS_root/jobs/sdpesp-dev-cvx/azureml/7d68a66e-aa64-4732-a159-22d477774715/wd/7d68a66e-aa64-4732-a159-22d477774715/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/partition_by_keys_provider.py", line 70, in get_tasks
    DatasetHelper().save(dataset)
  File "/mnt/batch/tasks/shared/LS_root/jobs/sdpesp-dev-cvx/azureml/7d68a66e-aa64-4732-a159-22d477774715/wd/azureml/7d68a66e-aa64-4732-a159-22d477774715/driver/azureml_common/parallel_run/dataset_helper.py", line 29, in save
    self.logger.info("Dump dataset {} as preppy files to local directory.".format(dataset.id))
AttributeError: 'str' object has no attribute 'id'

Could this possibly be an issue with `ParallelRunStep` being unable to accept a partitioned `OutputDatasetConfig` as an `input`? Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f69044d5-213e-a764-31dd-24f8368212b7
* Version Independent ID: 23d38b1c-974a-b2fc-332a-70d7500e1751
* Content: [azureml.pipeline.steps.ParallelRunStep class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.parallelrunstep?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.ParallelRunStep.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.ParallelRunStep.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by caitriggs** [comment]
Having the same issue with creating a pipeline using a ParallelRunStep. Cannot use an output from previous step as input to ParallelRunStep as documented in this issue

**Comment by caitriggs** [comment]
@jtisbell4 what work around did you end up using?

**Comment by caitriggs** [comment]
We tried partitioning the intermediate OutputTabularDatasetConfig, but .partition_by() necessary for this ONLY takes a TabularDataset object. Can't find a workaround for partitioning a dataset from intermediate data within a pipeline run. Seems like splitting these 2 actions up into 2 pipelines is the only way to get around this bug

**Comment by caitriggs** [comment]
> To consume the output as an input in subsequent pipeline steps, you may need to call as_input() https://learn.microsoft.com/en-us/python/api/azureml-core/azureml.data.output_dataset_config.outputdatasetconfig?view=azure-ml-py

this isn't the problem in this case. Even if you did add .as_input() to the OutputTabularDatasetConfig when passing it into the subsequent ParallelRunStep, you still need to pass that OutputConfig in as an already partitioned dataset - TabularDataset.partition_by() - but you cannot call .partition_by() on an OutputConfig type object

![image](https://user-images.githubusercontent.com/6527200/218274127-c4dde5bb-0ca0-492c-b410-3527ab58e61f.png)
