### ISSUE TITLE
Current example of HyperDriveStep does not fully populate all of the model parameters

### ISSUE THREAD

**Issue by edgBR** [Azure/MachineLearningNotebooks#1702]
Dear colleagues,

I find the example provided here: 

https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-parameter-tuning-with-hyperdrive.ipynb

A bit dangerous. When registering the model like this the lineage tracking is broken and we can not see the run id and the experiment name that generate the model. 

I have found in some documentation (which honestly is a bit messy) and some answers in StackOverflow that in order to link the run id and experiment name we need to use:

```python
register_model(model_name, model_path=None, tags=None, properties=None, model_framework=None, model_framework_version=None, description=None, datasets=None, sample_input_dataset=None, sample_output_dataset=None, resource_configuration=None, **kwargs)
```

https://stackoverflow.com/questions/69838394/add-run-id-when-registering-ml-azure-model-via-python-pipeline

However this seems to cause problems.

Currently my register step looks like:

``` python
import argparse
import json
import os
from azureml.core import Workspace, Experiment, Model, Dataset
from azureml.core import Run
from shutil import copy2


parser = argparse.ArgumentParser()
parser.add_argument('--saved-model', type=str,
                     dest='saved_model', help='path to saved model file')
parser.add_argument("--ml_datafile", type=str,
                        help="Dataset file for training data",
                        default="train_data.csv")
parser.add_argument("--feature_metadata_file", type=str,
                        help="Dataset file for training data",
                        default="feature_metadata.csv")
parser.add_argument("--preprocessing_config_file", type=str,
                        help="Dataset file for training data",
                        default="preprocessing_config.json")
parser.add_argument("--model_name", type=str,
                        help="Dataset file for training data",
                        default="my_model")


args = parser.parse_args()

model_output_dir = './model/'

os.makedirs(model_output_dir, exist_ok=True)
copy2(args.saved_model, model_output_dir)

run = Run.get_context()
ws = Workspace.from_config() if not hasattr(run, 'experiment') else run.experiment.workspace

training_data = Dataset.get_by_name(
            ws, name=args.ml_datafile,
            version='latest')

feature_data = Dataset.get_by_name(
            ws, name=args.feature_metadata_file,
            version='latest')

preprocessing_data = Dataset.get_by_name(
    ws, name=args.preprocessing_config_file,
    version='latest'
)
#we should pass also the metrics file

model = run.register_model(
    model_name=args.model_name, 
    model_path=model_output_dir,
    datasets = [('training_data', training_data),
                ('feature_metadata', feature_data),
                ('preprocessing_configuration', preprocessing_data)])

```

However I get this error:

```python
Cleaning up all outstanding Run operations, waiting 300.0 seconds
0 items cleaning up...
Cleanup took 1.6689300537109375e-06 seconds
[stderr]Traceback (most recent call last):
[stderr]  File "register_best_model.py", line 31, in <module>
[stderr]    copy2(args.saved_model, model_output_dir)
[stderr]  File "/azureml-envs/azureml_da3e97fcb51801118b8e80207f3e01ad/lib/python3.6/shutil.py", line 257, in copy2
[stderr]    copyfile(src, dst, follow_symlinks=follow_symlinks)
[stderr]  File "/azureml-envs/azureml_da3e97fcb51801118b8e80207f3e01ad/lib/python3.6/shutil.py", line 120, in copyfile
[stderr]    with open(src, 'rb') as fsrc:
[stderr]FileNotFoundError: [Errno 2] No such file or directory: '/mnt/azureml/cr/j/978357d82fb348868ebe8219b2feaac7/cap/data-capability/wd/saved_model_initial_data_load/azureml/5ae56075-32ef-4f76-928a-a58df321ecbe/saved_model'
[stderr]

```

Which is nuts as when I do:

```python
model = Model.register(
    workspace=ws, 
    model_name='day_zero_ff_model_12', 
    model_path=model_output_dir)
```

Everything works normally. I am puzzled to understand why this change is causing the model artifact to not be copied properly. Any thoughts on how to log the run ids and experiment names in a different way?

**Comment by edgBR** [comment]
Hi,

Im closing this since we wrote from scratch a workaround.
