### ISSUE TITLE
Logging error with ds.as_download

### ISSUE THREAD

**Issue by lmiroslaw** [Azure/MachineLearningNotebooks#258]
Has anybody experienced a similar error? It happened during downloading large files to DSVM.

script_params = {
    '--path-template': ds_rphi.as_download(),
    '--template-pattern': 'rphi_eval_module_{}.dat',
    '--dir-weights': ds_weights.as_download(),
    '--truth-tracks-path': ds_tracks.as_download()
}
 
est = Estimator(source_directory=source_folder,
                script_params=script_params,
                compute_target=compute_target,  
                entry_script='dummy-tracker.py',
                pip_packages=['pynvrtc'],
                conda_packages=['pytorch','scipy','numpy','scikit-learn','tqdm','cython','torchvision'])

--- Logging error ---
Downloaded rphi/rphi_eval_module_20.dat, 8 files out of an estimated total of 53
Downloading rphi/rphi_eval_module_44.dat
Traceback (most recent call last):
  File "/azureml-envs/azureml_ef673c8a2e39a3a18eef1c1e42c58ccf/lib/python3.6/site-packages/azureml/data/azure_storage_datastore.py", line 256, in handler
    result = fn()
  File "/azureml-envs/azureml_ef673c8a2e39a3a18eef1c1e42c58ccf/lib/python3.6/site-packages/azureml/data/azure_storage_datastore.py", line 521, in <lambda>
    return lambda: self.blob_service.get_blob_to_path(self.container_name, blob.name, dest)
  File "/azureml-envs/azureml_ef673c8a2e39a3a18eef1c1e42c58ccf/lib/python3.6/site-packages/azureml/_vendor/azure_storage/blob/baseblobservice.py", line 1872, in get_blob_to_path
    timeout)
  File "/azureml-envs/azureml_ef673c8a2e39a3a18eef1c1e42c58ccf/lib/python3.6/site-packages/azureml/_vendor/azure_storage/blob/baseblobservice.py", line 2054, in get_blob_to_stream
    stream.write(b

**Comment by j-martens** [comment]
Thanks for your report. Are you still experiencing this issue? Have you posted on the forum https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=AzureMachineLearningService?

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us. We see our answer was delayed. Our apologies. We did not receive a response to our post, so will close this issue for now. Should you need further assistance, please submit a post on this forum and we will respond promptly.
