### ISSUE TITLE
PyTorch hyperparameter tuning example doesn't run out of the box

### ISSUE THREAD

**Issue by cathywu** [Azure/MachineLearningNotebooks#331]
Running the `train-hyperparameter-tune-deploy-with-pytorch` tutorial (via Azure Notebooks) at the submit job step (`run = experiment.submit(estimator)`) yields the following error (after successfully downloading and extracting the data):

```
100.0%
Epoch 0/29
----------
train Loss: 0.5902 Acc: 0.6803


The experiment failed. Finalizing run...
Logging experiment finalizing status in history service
Cleaning up all outstanding Run operations, waiting 300.0 seconds
2 items cleaning up...
Cleanup took 0.5015969276428223 seconds
Traceback (most recent call last):
  File "azureml-setup/context_manager_injector.py", line 161, in <module>
    execute_with_context(cm_objects, options.invocation)
  File "azureml-setup/context_manager_injector.py", line 90, in execute_with_context
    runpy.run_path(sys.argv[0], globals(), run_name="__main__")
  File "/azureml-envs/azureml_b597eaa6db1a149b61fa829fc32fb56d/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/azureml-envs/azureml_b597eaa6db1a149b61fa829fc32fb56d/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/azureml-envs/azureml_b597eaa6db1a149b61fa829fc32fb56d/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "pytorch_train.py", line 206, in <module>
    main()
  File "pytorch_train.py", line 200, in main
    args.learning_rate, args.momentum)
  File "pytorch_train.py", line 158, in fine_tune_model
    exp_lr_scheduler, num_epochs, data_dir)
  File "pytorch_train.py", line 84, in train_model
    for inputs, labels in dataloaders[phase]:
  File "/azureml-envs/azureml_b597eaa6db1a149b61fa829fc32fb56d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/azureml-envs/azureml_b597eaa6db1a149b61fa829fc32fb56d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
UnboundLocalError: Traceback (most recent call last):
  File "/azureml-envs/azureml_b597eaa6db1a149b61fa829fc32fb56d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/azureml-envs/azureml_b597eaa6db1a149b61fa829fc32fb56d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/azureml-envs/azureml_b597eaa6db1a149b61fa829fc32fb56d/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 101, in __getitem__
    sample = self.loader(path)
  File "/azureml-envs/azureml_b597eaa6db1a149b61fa829fc32fb56d/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 147, in default_loader
    return pil_loader(path)
  File "/azureml-envs/azureml_b597eaa6db1a149b61fa829fc32fb56d/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 129, in pil_loader
    img = Image.open(f)
  File "/azureml-envs/azureml_b597eaa6db1a149b61fa829fc32fb56d/lib/python3.6/site-packages/PIL/Image.py", line 2690, in open
    im = _open_core(fp, filename, prefix)
  File "/azureml-envs/azureml_b597eaa6db1a149b61fa829fc32fb56d/lib/python3.6/site-packages/PIL/Image.py", line 2676, in _open_core
    im = factory(fp, filename)
  File "/azureml-envs/azureml_b597eaa6db1a149b61fa829fc32fb56d/lib/python3.6/site-packages/PIL/JpegImagePlugin.py", line 783, in jpeg_factory
    im = JpegImageFile(fp, filename)
  File "/azureml-envs/azureml_b597eaa6db1a149b61fa829fc32fb56d/lib/python3.6/site-packages/PIL/ImageFile.py", line 103, in __init__
    self._open()
  File "/azureml-envs/azureml_b597eaa6db1a149b61fa829fc32fb56d/lib/python3.6/site-packages/PIL/JpegImagePlugin.py", line 373, in _open
    handler(self, i)
  File "/azureml-envs/azureml_b597eaa6db1a149b61fa829fc32fb56d/lib/python3.6/site-packages/PIL/JpegImagePlugin.py", line 139, in APP
    self.info["photoshop"] = photoshop
UnboundLocalError: local variable 'photoshop' referenced before assignment
```

**Comment by j-martens** [comment]
Thanks for your report. Are you still experiencing this issue?

**Comment by cathywu** [comment]
Thanks for the follow up. I believe I ended up using a different example in
the meantime.

**Comment by j-martens** [comment]
Thanks!
