### ISSUE TITLE
Error while cleaning up resources after training in HDInsight Spark cluster

### ISSUE THREAD

**Issue by rbobadilla** [Azure/MachineLearningNotebooks#365]
I'm training a sample experiment in AMLS. My goal is to run it in a remote hdi cluster with python3.

I manually installed all the libraries that needed on the cluster (both in head nodes and worker nodes).

By checking the logs files created for in each run I can see that it completed succesfully, but for some reason, the run took a failed status.

After running, cluster starts cleaning the resources, and it semms it looks for a /output folder into /users/sshuser.
This is the error message:
---------------------------------------------------------------------------------------------
The experiment completed successfully. Finalizing run...
Cleaning up all outstanding Run operations, waiting 300.0 seconds
2 items cleaning up...
Cleanup took 0.5020554065704346 seconds
Traceback (most recent call last):
  File "context_manager_injector.py", line 160, in <module>
    execute_with_context(cm_objects, options.invocation)
  File "context_manager_injector.py", line 113, in execute_with_context
    log_finalizing()
  File "/mnt/resource/hadoop/yarn/local/usercache/sshuser/appcache/application_1557328483739_0005/container_1557328483739_0005_01_000001/azureml_c876362074e4ef12eac17653e81a4b83.zip/home/sshuser/.azureml/envs/azureml_c876362074e4ef12eac17653e81a4b83/lib/python3.6/contextlib.py", line 380, in __exit__
    raise exc_details[1]
  File "/mnt/resource/hadoop/yarn/local/usercache/sshuser/appcache/application_1557328483739_0005/container_1557328483739_0005_01_000001/azureml_c876362074e4ef12eac17653e81a4b83.zip/home/sshuser/.azureml/envs/azureml_c876362074e4ef12eac17653e81a4b83/lib/python3.6/contextlib.py", line 365, in __exit__
    if cb(*exc_details):
  File "/mnt/resource/hadoop/yarn/local/usercache/sshuser/appcache/application_1557328483739_0005/container_1557328483739_0005_01_000001/azureml_c876362074e4ef12eac17653e81a4b83.zip/home/sshuser/.azureml/envs/azureml_c876362074e4ef12eac17653e81a4b83/lib/python3.6/contextlib.py", line 284, in _exit_wrapper
    return cm_exit(cm, *exc_details)
  File "context_manager_injector.py", line 43, in __exit__
    self.context_manager.__exit__(*exc_details)
  File "/mnt/resource/hadoop/yarn/local/usercache/sshuser/appcache/application_1557328483739_0005/container_1557328483739_0005_01_000001/context_managers.py", line 67, in __exit__
    self.history_context.__exit__(*args)
  File "/mnt/resource/hadoop/yarn/local/usercache/sshuser/appcache/application_1557328483739_0005/container_1557328483739_0005_01_000001/azureml_c876362074e4ef12eac17653e81a4b83.zip/home/sshuser/.azureml/envs/azureml_c876362074e4ef12eac17653e81a4b83/lib/python3.6/site-packages/azureml/_history/utils/context_managers.py", line 54, in __exit__
    return self._exit_stack.__exit__(*args)
  File "/mnt/resource/hadoop/yarn/local/usercache/sshuser/appcache/application_1557328483739_0005/container_1557328483739_0005_01_000001/azureml_c876362074e4ef12eac17653e81a4b83.zip/home/sshuser/.azureml/envs/azureml_c876362074e4ef12eac17653e81a4b83/lib/python3.6/contextlib.py", line 380, in __exit__
    raise exc_details[1]
  File "/mnt/resource/hadoop/yarn/local/usercache/sshuser/appcache/application_1557328483739_0005/container_1557328483739_0005_01_000001/azureml_c876362074e4ef12eac17653e81a4b83.zip/home/sshuser/.azureml/envs/azureml_c876362074e4ef12eac17653e81a4b83/lib/python3.6/contextlib.py", line 365, in __exit__
    if cb(*exc_details):
  File "/mnt/resource/hadoop/yarn/local/usercache/sshuser/appcache/application_1557328483739_0005/container_1557328483739_0005_01_000001/azureml_c876362074e4ef12eac17653e81a4b83.zip/home/sshuser/.azureml/envs/azureml_c876362074e4ef12eac17653e81a4b83/lib/python3.6/contextlib.py", line 284, in _exit_wrapper
    return cm_exit(cm, *exc_details)
  File "/mnt/resource/hadoop/yarn/local/usercache/sshuser/appcache/application_1557328483739_0005/container_1557328483739_0005_01_000001/azureml_c876362074e4ef12eac17653e81a4b83.zip/home/sshuser/.azureml/envs/azureml_c876362074e4ef12eac17653e81a4b83/lib/python3.6/site-packages/azureml/_history/utils/context_managers.py", line 140, in __exit__
    self.py_wd.track(self.run_tracker, self.trackfolders, self.deny_list)
  File "/mnt/resource/hadoop/yarn/local/usercache/sshuser/appcache/application_1557328483739_0005/container_1557328483739_0005_01_000001/azureml_c876362074e4ef12eac17653e81a4b83.zip/home/sshuser/.azureml/envs/azureml_c876362074e4ef12eac17653e81a4b83/lib/python3.6/site-packages/azureml/_history/utils/context_managers.py", line 93, in track
    fs.track(run_tracker, track_folders, blacklist)
  File "/mnt/resource/hadoop/yarn/local/usercache/sshuser/appcache/application_1557328483739_0005/container_1557328483739_0005_01_000001/azureml_c876362074e4ef12eac17653e81a4b83.zip/home/sshuser/.azureml/envs/azureml_c876362074e4ef12eac17653e81a4b83/lib/python3.6/site-packages/azureml/_history/utils/filesystem.py", line 138, in track
    self._upload_hdi_outputs(run_tracker)
  File "/mnt/resource/hadoop/yarn/local/usercache/sshuser/appcache/application_1557328483739_0005/container_1557328483739_0005_01_000001/azureml_c876362074e4ef12eac17653e81a4b83.zip/home/sshuser/.azureml/envs/azureml_c876362074e4ef12eac17653e81a4b83/lib/python3.6/site-packages/azureml/_history/utils/filesystem.py", line 177, in _upload_hdi_outputs
    upload_from_hdfs(run_tracker, track_prefix)
  File "/mnt/resource/hadoop/yarn/local/usercache/sshuser/appcache/application_1557328483739_0005/container_1557328483739_0005_01_000001/azureml_c876362074e4ef12eac17653e81a4b83.zip/home/sshuser/.azureml/envs/azureml_c876362074e4ef12eac17653e81a4b83/lib/python3.6/site-packages/azureml/_history/utils/_hdi_utils.py", line 63, in upload_from_hdfs
    aa = file_system.listFiles(path, True)
  File "/mnt/resource/hadoop/yarn/local/usercache/sshuser/appcache/application_1557328483739_0005/container_1557328483739_0005_01_000001/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/mnt/resource/hadoop/yarn/local/usercache/sshuser/appcache/application_1557328483739_0005/container_1557328483739_0005_01_000001/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/mnt/resource/hadoop/yarn/local/usercache/sshuser/appcache/application_1557328483739_0005/container_1557328483739_0005_01_000001/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o170.listFiles.
: java.io.FileNotFoundException: File/Folder does not exist: /clusters/hdipi36/user/sshuser/<experiment_name>1557330292_20ee084d/outputs [c963e3ed-e386-42dc-b771-61db38b2092d][2019-05-08T08:47:03.6900690-07:00] [ServerRequestId:c963e3ed-e386-42dc-b771-61db38b2092d]
	at sun.reflec

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was not addressed and was posted some time ago. Our apologies. Should you need assistance with another issue, please let us know and we will respond to your post promptly.
