### ISSUE TITLE
[AzureML][PyTorch] shm_size can't be modified

### ISSUE THREAD

**Issue by ZekunZh** [Azure/MachineLearningNotebooks#560]
**Potential bug related to shm_size in azureml.train.dnn.PyTorch**

I tried to increase the `shm_size` of PyTorch to `4g` in order to run large batch training. However, the final run still has default `shm_size=2g`. My code to modify the `shm_size`
```
estimator = PyTorch(source_directory=".",
                    compute_target=compute_target,
                    entry_script="detector.py",
                    script_params=script_params,
                    use_gpu=True,
                    use_docker=True,
                    custom_docker_image=DOCKER_IMAGE,
                    image_registry_details=custom_cr,
                    shm_size="4g",
                    user_managed=True,
                    environment_variables={"CUDA_VISIBLE_DEVICES": "0,1,2,3"}
                    )
```

I verified that in `estimator.run_config.environment` that `shmSize` has been modified:
```
print(estimator.run_config.environment.docker.shm_size)
[Ouputs]
'4g'
```

However when I submitted the run and get run details, the `shmSize` falls back to `2g`, and the training will crash:
```
experiment_name = 'object_detection-low_priority'
experiment = Experiment(ws, name=experiment_name)

run = experiment.submit(estimator)
run.get_details()

[Outputs]
{...,
  'docker': {'arguments': [], 'sharedVolumes': True, 'shmSize': '2g'},
...,
}
```

Provide the following if applicable:
+ Python version: 3.5.6
+ Environment: torch==0.4.1, torchvision==0.2.1
+ Example data 
+ Error log:
```
  5%|4         | 263/5303 [00:01<00:26, 186.72it/s]
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).

The experiment failed. Finalizing run...
INFO context_manager_injector.py:  48: Exiting context: TrackUserError
INFO context_manager_injector.py:  48: Exiting context: RunHistory
INFO context_manager_injector.py:  48: Exiting context: ProjectPythonPath
Traceback (most recent call last):
  File "detector.py", line 270, in <module>
    detector.train(data_dir=args.data_dir, output_dir=args.output_dir)
  File "detector.py", line 79, in train
    train_model(cfg=self.cfg_train)
  File "/detectron/detectron_lib/train.py", line 167, in train_model
    cfg.TEST.DATASETS, cfg.TEST.PROPOSAL_FILES
  File "/detectron/detectron_lib/datasets/roidb.py", line 63, in combined_roidb_for_training
    roidbs = [get_roidb(*args) for args in zip(dataset_names, proposal_files)]
  File "/detectron/detectron_lib/datasets/roidb.py", line 63, in <listcomp>
    roidbs = [get_roidb(*args) for args in zip(dataset_names, proposal_files)]
  File "/detectron/detectron_lib/datasets/roidb.py", line 48, in get_roidb
    crowd_filter_thresh=cfg.TRAIN.CROWD_FILTER_THRESH
  File "/detectron/detectron_lib/datasets/json_dataset.py", line 128, in get_roidb
    self._prep_roidb_entry(entry)
  File "/detectron/detectron_lib/datasets/json_dataset.py", line 173, in _prep_roidb_entry
    assert os.path.exists(im_path), 'Image \'{}\' not found'.format(im_path)
  File "/opt/conda/envs/py35/lib/python3.5/genericpath.py", line 19, in exists
    os.stat(path)
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 227, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 442) is killed by signal: Bus error. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f84a6d15cc0>>
Traceback (most recent call last):
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 372, in _shutdown_workers
  File "/opt/conda/envs/py35/lib/python3.5/threading.py", line 519, in set
terminate called without an active exception
  File "/opt/conda/envs/py35/lib/python3.5/threading.py", line 362, in notify_all
  File "/opt/conda/envs/py35/lib/python3.5/threading.py", line 345, in notify
bash: line 1:   421 Aborted                 (core dumped) python $AZ_BATCHAI_JOB_MOUNT_ROOT/workspacefilestore/azureml/object_detection-low_priority_1567607204_e0a347de/azureml-setup/context_manager_injector.py "-i" "ProjectPythonPath:context_managers.ProjectPythonPath" "-i" "RunHistory:context_managers.RunHistory" "-i" "TrackUserError:context_managers.TrackUserError" "detector.py" "--data_dir" "$AZUREML_DATAREFERENCE_241433ae4d5d4682a74edaf112eba2a3" "--output_dir" "./outputs"
```

**To Reproduce**
1. Create an estimator of `azureml.train.dnn.PyTorch` with `shm_size='4g'`
2. Submit this estimator and print `run.get_details()`
3. Verify that if the docker has `shmSize: '4g'`

**Comment by ZekunZh** [comment]
[Update]
Today when I test the same code, it works without problem. Mysteriously the `shm_size` can be corretectly handled by Azure ML. I will close this issue.
![Screenshot from 2019-09-05 10-56-05](https://user-images.githubusercontent.com/16140400/64327384-ddeb3200-cfcb-11e9-83aa-eef080d9c656.png)
