### ISSUE TITLE
Url error in pytorch_train.py

### ISSUE THREAD

**Issue by njuHan** [Azure/MachineLearningNotebooks#674]
In pytorch_train.py, 
download_url = 'https://msdocsdatasets.blob.core.windows.net/pytorchfowl/fowl_data.zip'
seems not working.

Error message:
Traceback (most recent call last):
  File "pytorch_train.py", line 206, in <module>
    main()
  File "pytorch_train.py", line 197, in main
    data_dir = download_data()
  File "pytorch_train.py", line 170, in download_data
    urllib.request.urlretrieve(download_url, filename=data_file)
  File "/azureml-envs/azureml_092053a71c6957d84946d78a0bcbf8a8/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/azureml-envs/azureml_092053a71c6957d84946d78a0bcbf8a8/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/azureml-envs/azureml_092053a71c6957d84946d78a0bcbf8a8/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/azureml-envs/azureml_092053a71c6957d84946d78a0bcbf8a8/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/azureml-envs/azureml_092053a71c6957d84946d78a0bcbf8a8/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/azureml-envs/azureml_092053a71c6957d84946d78a0bcbf8a8/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/azureml-envs/azureml_092053a71c6957d84946d78a0bcbf8a8/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

**Comment by YutongTie-MSFT** [comment]
@njuHan Hi han, may I know which notebook you are referring to for this issue? Thanks.

**Comment by njuHan** [comment]
The notebook [train-hyperparameter-tune-deploy-with-pytorch](https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/ml-frameworks/pytorch/deployment/train-hyperparameter-tune-deploy-with-pytorch) had this issue.
But the download_url I mentioned has been updated in [this commit](https://github.com/Azure/MachineLearningNotebooks/commit/75610ec31cc83471e0eea10f13937a1e13a2b5ad#diff-c23e648112d29b673c31dec890d292f3) four days ago. 
So this issue has been fixed.
Thanks :-)

**Comment by neelamari** [comment]
The new link updated in commit is broken.
https://azureopendatastorage.blob.core.windows.net/testpublic/temp/fowl_data.zip
