### ISSUE TITLE
Can't build fastai within PyTorch estimator

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#705]
I thought using PyTorch would build things automatically!?
```python
estimator = PyTorch(
    source_directory='./compute',
    entry_script='train.py',
    script_params={
        '--data_folder': ds_file.as_named_input('ds_file').as_mount(),
        '--random_seed':42},
    inputs=[ds_lab.as_named_input('ds_lab')],
    compute_target=compute_target,
    use_gpu=True,
    framework_version='1.2',
    pip_packages=['fastai==1.0.59', 'pandas==0.25.3', 'azureml-dataprep[fuse]'])
```

### [`20_image_build_log.txt`](https://gist.github.com/swanderz/bd55e9c8feb150dac82560339a4f7165) excerpt
```
  gcc -pthread -shared -L/azureml-envs/azureml_53dd6592e1c9f7f3a2629ef34d81e971/lib -Wl,-rpath=/azureml-envs/azureml_53dd6592e1c9f7f3a2629ef34d81e971/lib,--no-as-needed -L/azureml-envs/azureml_53dd6592e1c9f7f3a2629ef34d81e971/lib -Wl,-rpath=/azureml-envs/azureml_53dd6592e1c9f7f3a2629ef34d81e971/lib,--no-as-needed build/temp.linux-x86_64-3.6/test_compile/test_nccl.o -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -L/azureml-envs/azureml_53dd6592e1c9f7f3a2629ef34d81e971/lib -lnccl_static -o build/temp.linux-x86_64-3.6/test_compile/test_nccl.so
  INFO: Unable to build TensorFlow plugin, will skip it.
  
  Traceback (most recent call last):
    File "/tmp/pip-install-m0ms6lxy/horovod/setup.py", line 55, in check_tf_version
      import tensorflow as tf
  ModuleNotFoundError: No module named 'tensorflow'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-m0ms6lxy/horovod/setup.py", line 909, in build_extensions
      build_tf_extension(self, options)
    File "/tmp/pip-install-m0ms6lxy/horovod/setup.py", line 608, in build_tf_extension
      check_tf_version()
    File "/tmp/pip-install-m0ms6lxy/horovod/setup.py", line 62, in check_tf_version
      'import tensorflow failed, is it installed?\n\n%s' % traceback.format_exc())
  distutils.errors.DistutilsPlatformError: import tensorflow failed, is it installed?
  
  Traceback (most recent call last):
    File "/tmp/pip-install-m0ms6lxy/horovod/setup.py", line 55, in check_tf_version
      import tensorflow as tf
  ModuleNotFoundError: No module named 'tensorflow'
  
  
  INFO: Unable to build PyTorch plugin, will skip it.
  
  Traceback (most recent call last):
    File "/tmp/pip-install-m0ms6lxy/horovod/setup.py", line 711, in check_torch_version
      import torch
  ModuleNotFoundError: No module named 'torch'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-m0ms6lxy/horovod/setup.py", line 920, in build_extensions
      torch_version = check_torch_version()
    File "/tmp/pip-install-m0ms6lxy/horovod/setup.py", line 718, in check_torch_version
      'import torch failed, is it installed?\n\n%s' % traceback.format_exc())
  distutils.errors.DistutilsPlatformError: import torch failed, is it installed?
  
  Traceback (most recent call last):
    File "/tmp/pip-install-m0ms6lxy/horovod/setup.py", line 711, in check_torch_version
      import torch
  ModuleNotFoundError: No module named 'torch'
  
  
  INFO: Unable to build MXNet plugin, will skip it.
  
  Traceback (most recent call last):
    File "/tmp/pip-install-m0ms6lxy/horovod/setup.py", line 71, in check_mx_version
      import mxnet as mx
  ModuleNotFoundError: No module named 'mxnet'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-m0ms6lxy/horovod/setup.py", line 935, in build_extensions
      build_mx_extension(self, options)
    File "/tmp/pip-install-m0ms6lxy/horovod/setup.py", line 672, in build_mx_extension
      check_mx_version()
    File "/tmp/pip-install-m0ms6lxy/horovod/setup.py", line 78, in check_mx_version
      'import mxnet failed, is it installed?\n\n%s' % traceback.format_exc())
  distutils.errors.DistutilsPlatformError: import mxnet failed, is it installed?
  
  Traceback (most recent call last):
    File "/tmp/pip-install-m0ms6lxy/horovod/setup.py", line 71, in check_mx_version
      import mxnet as mx
  ModuleNotFoundError: No module named 'mxnet'
  
  
  error: None of TensorFlow, PyTorch, or MXNet plugins were built. See errors above.
  ----------------------------------------
  ERROR: Failed building wheel for horovod
```
@rastala

**Comment by YutongTie-MSFT** [comment]
@swanderz 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by rastala** [comment]
It appears that latest pillow package version had breaking changes that resulted in failing import. Pinning pillow to earlier version should resolve the issue:

pip_packages=['fastai==1.0.59', 'pandas==0.25.3', 'azureml-dataprep[fuse]','pillow==6.1'])

**Comment by swanderz** [comment]
confirmed. thanks!
