### ISSUE TITLE
AzureML service reload() throws exception with local deployment (using LocalWebservice)

### ISSUE THREAD

**Issue by adiun** [Azure/MachineLearningNotebooks#714]
I previously did a local deployment through the CLI `az ml model deploy`, using a local deployment configuration. Through the SDK I am trying to get a handle to that existing, locally-deployed service with `LocalWebservice()` and run a `reload` on that :

```python
    svc = LocalWebservice(workspace, service_name)
    print(svc.reload())
```

This throws an error:

```
Traceback (most recent call last):
  File "/opt/conda/bin/inv", line 10, in <module>
    sys.exit(program.run())
  File "/opt/conda/lib/python3.7/site-packages/invoke/program.py", line 363, in run
    self.execute()
  File "/opt/conda/lib/python3.7/site-packages/invoke/program.py", line 532, in execute
    executor.execute(*self.tasks)
  File "/opt/conda/lib/python3.7/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/opt/conda/lib/python3.7/site-packages/invoke/tasks.py", line 128, in __call__
    result = self.body(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/empowermdamltools/tasks/aml.py", line 121, in badReload
    svc.reload()
  File "/opt/conda/lib/python3.7/site-packages/azureml/core/webservice/local.py", line 71, in decorated
    return func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/azureml/core/webservice/local.py", line 407, in reload
    self._run_container(wait=wait)
  File "/opt/conda/lib/python3.7/site-packages/azureml/core/webservice/local.py", line 934, in _run_container
    posixpath.join(MODEL_PACKAGE_MODELS_DIR, self._model_path_dir),
AttributeError: 'LocalWebservice' object has no attribute '_model_path_dir'
```

This actually ends up stopping and deleting the Docker container corresponding to the running service too!

I noticed that I can use this approach (getting a handle to the existing service through the `LocalWebservice` ctor) for getting logs without error even though the other `reload()` call fails:

```python
    svc = LocalWebservice(workspace, service_name)
    print(svc.get_logs())
```

In a Jupyter notebook, it's possible to do a `Model.deploy` to get a `service` through the SDK, get the handle to the `service` and call `reload` on it. This works fine, but if I am writing code that interacts with the AzureML SDK in my IDE, I want to be able to deploy the service, change some code in the entry script, and then call reload on it without maintaining a handle to the `service` coming out of `Model.deploy`.

The only way it seems I can make this work right now is to deploy the service via `Model.deploy` and immediately start a long-running "watch" process that can access that `service` var to `reload()` - this workaround works, but is not ideal.

**Comment by YutongTie-MSFT** [comment]
@adiun 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by jpe316** [comment]
@mrudulan

**Comment by shivanissambare** [comment]
closing this issue as it is open from Dec 2019.
@adiun if you are still facing the problem, please feel to re-open and lmk :)
