### ISSUE TITLE
Datastore.get() -> ResponseError('too many 504 error responses',)

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#725]
Trying to get info on Datastore results in error (in both SDK and in Portal UX).

Looks like its a blob service issue that I've only been experiencing for the past few hours, but flagging here anyway....

@MayMSFT @rastala @lostmygithubaccount 

```python
ds_pipeline = Datastore.get(ws, datastore_name='deal_pipeline_blob')
```
error
```
ClientRequestError: Error occurred in request.,
RetryError: HTTPSConnectionPool(host='westus2.experiments.azureml.net', port=443):
    Max retries exceeded with url: /datastore/v1.0/subscriptions/ff2e23ae-7d7c-4cbd-99b8-116bs.azureml.net', port=443):
    Max retries exceeded with url: /datastore/v1.0/subscriptions/ff2e23ae-7d7c-4csmlsvc/datastores/deal_pipeline_blob
(Caused by ResponseError('too many 504 error responses',))
bd-99b8-116bb94dca6e/resourceGroups/RG-ITSMLTeam-Dev/providers/Microsoft.MachineLearningServices/workspaces/avadevitsmlsvc/datastores/deal_pipeline_blob
(Caused by ResponseError('too many 504 error responses',))
```
also happens in UX after minute or loading message
![image](https://user-images.githubusercontent.com/8158673/71874816-b91cdd80-30d7-11ea-8aed-06a1e8249255.png)

### full stack trace (SDK)
```python
WARNING - Retrying (Retry(total=0, connect=3, read=2, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='westus2.experiments.azureml.net', port=443): Read timed out. (read timeout=100)",)': /datastore/v1.0/subscriptions/ff2e23ae-7d7c-4cbd-99b8-116bb94dca6e/resourceGroups/RG-ITSMLTeam-Dev/providers/Microsoft.MachineLearningServices/workspaces/avadevitsmlsvc/datastores/deal_pipeline_blob
---------------------------------------------------------------------------
MaxRetryError                             Traceback (most recent call last)
c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    448                     retries=self.max_retries,
--> 449                     timeout=timeout
    450                 )

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    845                 body_pos=body_pos,
--> 846                 **response_kw
    847             )

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    845                 body_pos=body_pos,
--> 846                 **response_kw
    847             )

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    759                 body_pos=body_pos,
--> 760                 **response_kw
    761             )

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    818             try:
--> 819                 retries = retries.increment(method, url, response=response, _pool=self)
    820             except MaxRetryError:

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\urllib3\util\retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    435         if new_retry.is_exhausted():
--> 436             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    437

MaxRetryError: HTTPSConnectionPool(host='westus2.experiments.azureml.net', port=443): Max retries exceeded with url: /datastore/v1.0/subscriptions/ff2e23ae-7d7c-4cbd-99b8-116bb94dca6e/resourceGroups/RG-ITSMLTeam-Dev/providers/Microsoft.MachineLearningServices/workspaces/avadevitsmlsvc/datastores/deal_pipeline_blob (Caused by ResponseError('too many 504 error responses',))

During handling of the above exception, another exception occurred:

RetryError                                Traceback (most recent call last)
c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\msrest\universal_http\requests.py in send(self, request, **kwargs)
    141                 request.url,
--> 142                 **kwargs)
    143         except requests.RequestException as err:

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\requests\sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    532         send_kwargs.update(settings)
--> 533         resp = self.send(prep, **send_kwargs)
    534

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    645         # Send the request
--> 646         r = adapter.send(request, **kwargs)
    647

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    506             if isinstance(e.reason, ResponseError):
--> 507                 raise RetryError(e, request=request)
    508

RetryError: HTTPSConnectionPool(host='westus2.experiments.azureml.net', port=443): Max retries exceeded 
with url: /datastore/v1.0/subscriptions/ff2e23ae-7d7c-4cbd-99b8-116bb94dca6e/resourceGroups/RG-ITSMLTeam-Dev/providers/Microsoft.MachineLearningServices/workspaces/avadevitsmlsvc/datastores/deal_pipeline_blob (Caused by ResponseError('too many 504 error responses',))

During handling of the above exception, another exception occurred:

ClientRequestError                        Traceback (most recent call last)
c:\Users\anders.swanson\Documents\deal\pipeline_multi.py in <module>
    190
    191 # %%
--> 192 ds_pipeline = Datastore.get(ws, datastore_name='deal_pipeline_blob')
    193 ds_output_blob = Datastore.get(ws, datastore_name='deal_output_blob')
    194

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\azureml\core\datastore.py in get(workspace, datastore_name)
    125                 or azureml.data.azure_storage_datastore.AzureBlobDatastore
    126         """
--> 127         return Datastore._client().get(workspace, datastore_name)
    128 
    129     @staticmethod

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\azureml\data\datastore_client.py in get(workspace, datastore_name)
     63         :rtype: AzureFileDatastore or AzureBlobDatastore
     64         """
---> 65         return _DatastoreClient._get(workspace, datastore_name)
     66 
     67     @staticmethod

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\azureml\data\datastore_client.py in _get(ws, name, auth, host)
    530         client = _DatastoreClient._get_client(ws, auth, host)
    531         datastore = client.data_stores.get(name, ws._subscription_id, ws._resource_group, ws._workspace_name,
--> 532                                            custom_headers=_DatastoreClient._custom_headers)     
    533 
    534         module_logger.debug("Received DTO from the datastore service")

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\azureml\_restclient\operations\data_stores_operations.py in get(self, name, subscription_id, resource_group_name, workspace_name, custom_headers, raw, **operation_config)
    284         # Construct and send request
    285         request = self._client.get(url, query_parameters)
--> 286         response = self._client.send(request, header_parameters, stream=False, **operation_config)
    287
    288         if response.status_code not in [200]:

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\msrest\service_client.py in send(self, request, headers, content, **kwargs)
    334         kwargs.setdefault('stream', True)
    335         try:
--> 336             pipeline_response = self.config.pipeline.run(request, **kwargs)
    337             # There is too much thing that expects this method to return a "requests.Response"  
    338             # to break it in a compatible release.

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\msrest\pipeline\__init__.py in run(self, request, **kwargs)
    195         pipeline_request = Request(request, context)  # type: Request[HTTPRequestType]
    196         first_node = self._impl_policies[0] if self._impl_policies else self._sender
--> 197         return first_node.send(pipeline_request, **kwargs)  # type: ignore
    198
    199 class HTTPSender(AbstractContextManager, ABC, Generic[HTTPRequestType, HTTPResponseType]):

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\msrest\pipeline\__init__.py in send(self, request, **kwargs)
    148         self._policy.on_request(request, **kwargs)
    149         try:
--> 150             response = self.next.send(request, **kwargs)
    151         except Exception:
    152             if not self._policy.on_exception(request, **kwargs):

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\msrest\pipeline\requests.py in send(self, request, **kwargs)
     70         try:
     71             try:
---> 72                 return self.next.send(request, **kwargs)
     73             except (oauth2.rfc6749.errors.InvalidGrantError,
     74                     oauth2.rfc6749.errors.TokenExpiredError) as err:

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\msrest\pipeline\requests.py in send(self, request, **kwargs)
    135 
    136         try:
--> 137             return self.next.send(request, **kwargs)
    138         finally:
    139             if old_max_redirects:

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\msrest\pipeline\__init__.py in send(self, request, **kwargs)
    148         self._policy.on_request(request, **kwargs)
    149         try:
--> 150             response = self.next.send(request, **kwargs)
    151         except Exception:
    152             if not self._policy.on_exception(request, **kwargs):

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\msrest\pipeline\requests.py in send(self, request, **kwargs)
    191         return Response(
    192             request,
--> 193             self.driver.send(request.http_request, **kwargs)
    194         )

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\msrest\universal_http\requests.py in send(self, request, **kwargs)
    331         """
    332         requests_kwargs = self._configure_send(request, **kwargs)
--> 333         return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
    334
    335

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\msrest\universal_http\requests.py in send(self, request, **kwargs)
    143         except requests.RequestException as err:
    144             msg = "Error occurred in request."
--> 145             raise_with_traceback(ClientRequestError, msg, err)
    146
    147         return RequestsClientResponse(request, response)

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\msrest\exceptions.py in raise_with_traceback(exception, message, *args, **kwargs)
     49     error = exception(exc_msg, *args, **kwargs)
     50     try:
---> 51         raise error.with_traceback(exc_traceback)
     52     except AttributeError:
     53         error.__traceback__ = exc_traceback

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\msrest\universal_http\requests.py in send(self, request, **kwargs)
    140                 request.method,
    141                 request.url,
--> 142                 **kwargs)
    143         except requests.RequestException as err:
    144             msg = "Error occurred in request."

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\requests\sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    531         }
    532         send_kwargs.update(settings)
--> 533         resp = self.send(prep, **send_kwargs)
    534
    535         return resp

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    644 
    645         # Send the request
--> 646         r = adapter.send(request, **kwargs)
    647
    648         # Total elapsed time of the request (approximately)

c:\users\anders.swanson\appdata\local\continuum\miniconda3\envs\deal_aml74\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    505
    506             if isinstance(e.reason, ResponseError):
--> 507                 raise RetryError(e, request=request)
    508
    509             if isinstance(e.reason, _ProxyError):

ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='westus2.experiments.azureml.net', port=443): Max retries exceeded with url: /datastore/v1.0/subscriptions/ff2e23ae-7d7c-4cbd-99b8-116bs.azureml.net', port=443): Max retries exceeded with url: /datastore/v1.0/subscriptions/ff2e23ae-7d7c-4csmlsvc/datastores/deal_pipeline_blob (Caused by ResponseError('too many 504 error responses',))bd-99b8-116bb94dca6e/resourceGroups/RG-ITSMLTeam-Dev/providers/Microsoft.MachineLearningServices/workspaces/avadevitsmlsvc/datastores/deal_pipeline_blob (Caused by ResponseError('too many 504 error responses',))
```

### [full stack trace (UX) ](https://gist.github.com/swanderz/c42b1373e9ab2c13033a12d50f4dcc08) exceprt
```json
  "innerError": {
    "stack": "Error: Credential service failed\n    at new t (https://ml.azure.com/static/js/140.79977918.chunk.js:1:659287)\n    at https://ml.azure.com/static/js/140.79977918.chunk.js:1:5402628",
    "message": "Credential service failed",
    "code": "ServiceError",
    "statusCode": 502,
    "request": {
      "streamResponseBody": false,
      "url": "https://westus2.experiments.azureml.net/datastore/v1.0/subscriptions/ff2e23ae-7d7c-4cbd-99b8-116bb94dca6e/resourceGroups/RG-ITSMLTeam-Dev/providers/Microsoft.MachineLearningServices/workspaces/avadevitsmlsvc/datastores/deal_pipeline_blob",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "content-type": {
            "name": "content-type",
            "value": "application/json; charset=utf-8"
          },
          "x-ms-command-name": {
            "name": "x-ms-command-name",
            "value": "/ ms-rest-js/1.8.13 OS/Win32"
          }
        }
      },
```

**Comment by swanderz** [comment]
this issue has resolved itself. closing now

**Comment by BillmanH** [comment]
I'm experiencing a similar issue with an experiment run: 

```python
Traceback (most recent call last):
  File "run_models.py", line 200, in <module>
    args.experiment_name)
  File "run_models.py", line 110, in main
    model, tags = callout.getModel(ws, pass_info, df)
  File "/mnt/batch/tasks/shared/LS_root/jobs/pjx-d-cu1-mlw-models/azureml/b85ff274-7b6a-4569-a4fd-dcf25a419036/mounts/workspaceblobstore/azureml/b85ff274-7b6a-4569-a4fd-dcf25a419036/callout.py", line 43, in getModel
    ws, id=pass_info['model_name']+":" + str(pass_info['version']))
  File "/azureml-envs/azureml_d7f8bdb28c1c8b0974cba340b242ff06/lib/python3.6/site-packages/azureml/core/model.py", line 155, in __init__
    get_response_payload = self._get(workspace, name, id, tags, properties, version, model_framework, run_id)
  File "/azureml-envs/azureml_d7f8bdb28c1c8b0974cba340b242ff06/lib/python3.6/site-packages/azureml/core/model.py", line 333, in _get
    logger=module_logger)
azureml.exceptions._azureml_exception.WebserviceException: WebserviceException:
	Message: Received bad response from Model Management Service:
Response Code: 504
Headers: {'Date': 'Tue, 07 Jan 2020 23:09:46 GMT', 'Content-Type': 'text/html', 'Content-Length': '160', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n'
	InnerException None
	ErrorResponse {"error": {"message": "Received bad response from Model Management Service:\nResponse Code: 504\nHeaders: {'Date': 'Tue, 07 Jan 2020 23:09:46 GMT', 'Content-Type': 'text/html', 'Content-Length': '160', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}\nContent: b'<html>\\r\\n<head><title>504 Gateway Time-out</title></head>\\r\\n<body>\\r\\n<center><h1>504 Gateway Time-out</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n'"}}
```

**Comment by BillmanH** [comment]
Looking in the code we found that this happens when the models are loaded for predicting:
Models service has this error:
```Python
REQUEST_SEND_ERROR : Failed to send request to https://westus2.modelmanagement.azureml.net/modelmanagement/v1.0/subscriptions/3465b147-e7ee-497a-8279-774442465d07/resourceGroups/Project_X_Dev/providers/Microsoft.MachineLearningServices/workspaces/pjx-d-cu1-mlw-models/models?orderBy=CreatedAtDesc.

```

**Comment by MayMSFT** [comment]
Hi @BillmanH , it should be a transient issue caused by our service. can you try again to see whether the issue persist? thanks

**Comment by BillmanH** [comment]
Yea,  I ran again in the morning and it completed. Is this likely to happen a lot? Does MLS have any SLA on uptime?

**Comment by swanderz** [comment]
I'm also now seeing this while waitig for a StepRun to finish. fortunately it resolved before failing the entire pipeline
```
StepRun( Download Dataset ) Status: Running
WARNING - Retrying (Retry(total=2, connect=3, read=2, redirect=None, status=None)) after connection broken by
'ReadTimeoutError("HTTPSConnectionPool(host='westus2.experiments.azureml.net', port=443): Read timed out. (read timeout=100)",)':
/history/v1.0/subscriptions/ff2e23ae-7d7c-4cbd-99b8-116bb94dca6e/resourceGroups/RG-ITSMLTeam-Dev/providers/Microsoft.MachineLearningServices/workspaces/avadevitsmlsvc/experiments/ret-doslasheswork/runs/774b2715-6651-47dc-8d65-786b0305d35c/details
```
clicking on the link in the portal gives me:
```
REQUEST_SEND_ERROR :
Failed to send request to
https://westus2.modelmanagement.azureml.net/modelmanagement/v1.0/subscriptions/ff2e23ae-7d7c-4cbd-99b8-116bb94dca6e/resourceGroups/RG-ITSMLTeam-Dev/providers/Microsoft.MachineLearningServices/workspaces/avadevitsmlsvc/models?runId=774b2715-6651-47dc-8d65-786b0305d35c&orderBy=CreatedAtDesc.
```
