### ISSUE TITLE
Deployments Hang and Fail

### ISSUE THREAD

**Issue by csteegz** [Azure/MachineLearningNotebooks#775]
Deployments using `model.deploy` will fail and hang. 

When looking at the logs, the error is 

```
Exception in worker process
Traceback (most recent call last):
  File "/azureml-envs/azureml_5ba93acc07411bf95cbe671b363e61d3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/azureml-envs/azureml_5ba93acc07411bf95cbe671b363e61d3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/azureml-envs/azureml_5ba93acc07411bf95cbe671b363e61d3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/azureml-envs/azureml_5ba93acc07411bf95cbe671b363e61d3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/azureml-envs/azureml_5ba93acc07411bf95cbe671b363e61d3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/azureml-envs/azureml_5ba93acc07411bf95cbe671b363e61d3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/azureml-envs/azureml_5ba93acc07411bf95cbe671b363e61d3/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/var/azureml-server/wsgi.py", line 3, in <module>
    app = create_app.create()
  File "/var/azureml-server/create_app.py", line 8, in create
    app.register_blueprint(main)
  File "/azureml-envs/azureml_5ba93acc07411bf95cbe671b363e61d3/lib/python3.6/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/azureml-envs/azureml_5ba93acc07411bf95cbe671b363e61d3/lib/python3.6/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/var/azureml-server/aml_blueprint.py", line 175, in register
    init_debugablity(self.logger, app)
  File "/var/azureml-server/debugablity/__init__.py", line 10, in init_debugablity
    for finder, name, ispkg in pkgutil.iter_modules([os.path.dirname(os.path.realpath(__file__))])
  File "/var/azureml-server/debugablity/__init__.py", line 11, in <dictcomp>
    if name.startswith('dbg_')
  File "/azureml-envs/azureml_5ba93acc07411bf95cbe671b363e61d3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/var/azureml-server/debugablity/dbg_model_info.py", line 4, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property'
```
Requiring `werkzeug==0.16.1` by adding it to the pip_dependencies in the environment with
```
environment.python.conda_dependencies.add_pip_dependency("werkzeug==0.16.1")
```

allows deployments to work.

**Comment by YutongTie-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.
