### ISSUE TITLE
Random invalid token error using Databricks PAT token

### ISSUE THREAD

**Issue by robinvdheijden** [Azure/MachineLearningNotebooks#840]
A PAT token is used to connect from Azure ML to Databricks. In the DevOps pipeline, this PAT token is successfully used in a couple of steps (configure cluster, copy notebook to cluster), but when it wants to run the notebook on the cluster, an invalid token error occurs now and then. In this, the team could not detect a pattern when this error occurs. See stack trace and global overview of the steps in the Azure DevOps pipeline.

![image](https://user-images.githubusercontent.com/9076235/75972890-85421680-5ed4-11ea-9229-2de4d3bfcd8f.png)

```
> <html>
> <head>
> <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
> <title>Error 403 Invalid access token.</title>
> </head>
> <body><h2>HTTP ERROR 403</h2>
> <p>Problem accessing /api/2.0/jobs/runs/submit. Reason:
> <pre>    Invalid access token.</pre></p>
> </body>
> </html>
> , stack_trace:    at Microsoft.RelInfra.Extensions.HttpClientExtensions.EnsureSuccessStatusCodeAsync(HttpResponseMessage response, Boolean ensureStrictSuccess) in d:\dbs\sh\Ae\0212_144257\cmd\3\src\RelInfra\RelInfra.Common.Library\src\Extensions\HttpClientExtensions.cs:line 882
>    at Microsoft.RelInfra.Extensions.HttpClientExtensions.SendContentWithAuthHeaderAsync(HttpClient client, HttpMethod httpMethod, String serverPath, HttpContent content, String authToken, IDictionary`2 customHeaders) in d:\dbs\sh\Ae\0212_144257\cmd\3\src\RelInfra\RelInfra.Common.Library\src\Extensions\HttpClientExtensions.cs:line 527
>    at Microsoft.RelInfra.Extensions.HttpClientExtensions.SendEntityWithAuthHeaderAsync[T](HttpClient client, HttpMethod httpMethod, String serverPath, T entity, String authToken, IDictionary`2 customHeaders) in d:\dbs\sh\Ae\0212_144257\cmd\3\src\RelInfra\RelInfra.Common.Library\src\Extensions\HttpClientExtensions.cs:line 485
>    at Microsoft.RelInfra.Extensions.HttpClientExtensions.SendEntityWithAuthHeaderAsync[T,TRet](HttpClient client, HttpMethod httpMethod, String serverPath, T entity, String authToken, IDictionary`2 customHeaders) in d:\dbs\sh\Ae\0212_144257\cmd\3\src\RelInfra\RelInfra.Common.Library\src\Extensions\HttpClientExtensions.cs:line 471
>    at Microsoft.RelInfra.Extensions.HttpClientExtensions.PostEntityWithAuthHeaderAsync[T,TRet](HttpClient client, String serverPath, T entity, String authToken, IDictionary`2 customHeaders)
>    at DataBricksCloudK8sService.DataBricksClient.DataBricksClient.<>c__DisplayClass11_0.<<SubmitRunAsync>b__0>d.MoveNext() in d:\dbs\sh\Ae\0212_144257\cmd\0\src\aether\platform\backendV2\BlueBox\Clouds\DataBricksK8s\Client\DataBricksClient.cs:line 42
>    at Microsoft.RelInfra.Common.RetryExecution.RetryExecutionHelper.ExecuteFuncWithRetryAsync[TRet](Func`1 function, Func`2 shouldRetryResult, Func`2 shouldRetryException, IRetryPolicy retryPolicy, CancellationToken token)
>    at Microsoft.RelInfra.Common.RetryExecution.RetryExecutionHelper.ExecuteFuncWithRetryAsync[TRet](Func`1 function, Func`2 shouldRetryException, IRetryPolicy retryPolicy, CancellationToken token)
>    at DataBricksCloudK8sService.DataBricksClient.DataBricksClient.SafeMethodCall[T,TRet](Func`1 function, IRetryPolicy retryPolicy)
>    at DataBricksCloudK8sService.DataBricksClient.DataBricksClient.SubmitRunAsync(SubmitRunDto submitRunDto) in d:\dbs\sh\Ae\0212_144257\cmd\0\src\aether\platform\backendV2\BlueBox\Clouds\DataBricksK8s\Client\DataBricksClient.cs:line 41
>    at Microsoft.Aether.DataBricksCloud.K8sService.JobProcessor.SubmitJobAsync(DataBricksJobMetadata job, SubmitRunDto submitRunDto) in d:\dbs\sh\Ae\0213_104627\cmd\t\src\aether\platform\backendV2\BlueBox\Clouds\DataBricksK8s\Service\JobProcessor.cs:line 235
> [2020-02-26 10:51:41Z] RunId:[xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] ParentRunId:[xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] ComputeTarget:[DataBricks]
```

**Comment by YutongTie-MSFT** [comment]
@robinvdheijden 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by robinvdheijden** [comment]
> @robinvdheijden
> Thanks for the feedback! We are currently investigating and will update you shortly.

Hi @YutongTie-MSFT 
Have you been able to learn anything as to what might have caused this occasional problem?

**Comment by jpe316** [comment]
@sanpil

**Comment by sanpil** [comment]
Most plausible reason for this seems to be a caching issue/bug on our side. We cache the PAT on our end in memory with the workspace identity/compute name as the key. If you de-attach and reattach the ADB compute using the same compute name but different ADB cluster/PAT, we could hit this. Can you confirm if this is the scenario?
