### ISSUE TITLE
Attribute Error while running automl experiment

### ISSUE THREAD

**Issue by electrozoa** [Azure/MachineLearningNotebooks#933]
I am running a continuous automl experiment and am getting the following error in each of the child runs for regression models

Subprocess (pid 157) exited with non-zero exit status 1. stderr output: 
Traceback (most recent call last):

  File "/azureml-envs/azureml_4e1233asg542cv6d20602cf92ad0f3b3/lib/python3.6/site-packages/azureml/automl/runtime/shared/spawn_server.py", line 79, in <module>

    run_server(config_file_name, input_file_name, output_file_name)

  File "/azureml-envs/azureml_4e5113bdc542cf6d20602cf92ad0f3b3/lib/python3.6/site-packages/azureml/automl/runtime/shared/spawn_server.py", line 40, in run_server

    import azureml.automl.runtime

  File "/azureml-envs/azureml_4e5113bdc542cf6d20602cf92ad0f3b3/lib/python3.6/site-packages/azureml/automl/__init__.py", line 5, in <module>

    import azureml.automl.core

  File "/azureml-envs/azureml_4e5113bdc542cf6d20602cf92ad0f3b3/lib/python3.6/site-packages/azureml/automl/core/__init__.py", line 16, in <module>

    _handle_legacy_shared_package_imports()

  File "/azureml-envs/azureml_4e5113bdc542cf6d20602cf92ad0f3b3/lib/python3.6/site-packages/azureml/automl/core/_shared_package_legacy_import.py", line 83, in _handle_legacy_shared_package_imports

    shared

  File "/azureml-envs/azureml_4e5113bdc542cf6d20602cf92ad0f3b3/lib/python3.6/site-packages/azureml/automl/core/_shared_package_legacy_import.py", line 105, in _import_all_legacy_submodules

    module = pkgutil.importlib.import_module(curr_package.__name__ + '.' + name)

  File "/azureml-envs/azureml_4e5113bdc542cf6d20602cf92ad0f3b3/lib/python3.6/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "/azureml-envs/azureml_4e5113bdc542cf6d20602cf92ad0f3b3/lib/python3.6/site-packages/azureml/automl/core/shared/forecasting_ts_utils.py", line 6, in <module>

    from azureml.automl.runtime.shared import forecasting_ts_utils

  File "/azureml-envs/azureml_4e5113bdc542cf6d20602cf92ad0f3b3/lib/python3.6/site-packages/azureml/automl/runtime/__init__.py", line 16, in <module>

    _handle_legacy_shared_package_imports()

  File "/azureml-envs/azureml_4e5113bdc542cf6d20602cf92ad0f3b3/lib/python3.6/site-packages/azureml/automl/runtime/_shared_package_legacy_import.py", line 29, in _handle_legacy_shared_package_imports

    shared

  File "/azureml-envs/azureml_4e5113bdc542cf6d20602cf92ad0f3b3/lib/python3.6/site-packages/azureml/automl/core/_shared_package_legacy_import.py", line 104, in _import_all_legacy_submodules

    for _, name, ispkg in pkgutil.walk_packages(curr_package.__path__):

  File "/azureml-envs/azureml_4e5113bdc542cf6d20602cf92ad0f3b3/lib/python3.6/pkgutil.py", line 92, in walk_packages

    __import__(info.name)

  File "/mnt/batch/tasks/shared/LS_root/jobs/hhalgoml/azureml/084b6edb-03ea-49d9-a47c-baf99bac7820_24/mounts/workspaceblobstore/azureml/084b6edb-03ea-49d9-a47c-baf99bac7820_24/score.py", line 4, in <module>

    import azureml.train.automl

  File "/azureml-envs/azureml_4e5113bdc542cf6d20602cf92ad0f3b3/lib/python3.6/site-packages/azureml/train/automl/__init__.py", line 28, in <module>

    from azureml.train.automl.automlconfig import AutoMLConfig

  File "/azureml-envs/azureml_4e5113bdc542cf6d20602cf92ad0f3b3/lib/python3.6/site-packages/azureml/train/automl/automlconfig.py", line 37, in <module>

    from ._remote_console_interface import RemoteConsoleInterface

  File "/azureml-envs/azureml_4e5113bdc542cf6d20602cf92ad0f3b3/lib/python3.6/site-packages/azureml/train/automl/_remote_console_interface.py", line 20, in <module>

    from ._azureautomlsettings import AzureAutoMLSettings

  File "/azureml-envs/azureml_4e5113bdc542cf6d20602cf92ad0f3b3/lib/python3.6/site-packages/azureml/train/automl/_azureautomlsettings.py", line 9, in <module>

    import azureml.automl.core.shared.exceptions as common_exceptions

AttributeError: module 'azureml' has no attribute 'automl'

**Comment by electrozoa** [comment]
these are my conda packages for environment

 cd = CondaDependencies.create(pip_packages=['azureml-sdk[automl]', 'applicationinsights','azureml-automl-core', 'azureml-opendatasets','xgboost==0.90','mysql-connector-python','azureml-defaults','joblib','azureml-automl-runtime'], 
                              conda_packages=['numpy==1.16.2',
                                             'pandas<=0.23.4,>=0.21.0',
                                             'scikit-learn<=0.20.3,>=0.19.0'], 
                              pin_sdk_version=True)
cd.add_pip_package('azureml-explain-model')

**Comment by electrozoa** [comment]
cd = CondaDependencies.create(pip_packages=['azureml-sdk[automl]', 'applicationinsights','azureml-automl-core', 'azureml-opendatasets','xgboost==0.90','mysql-connector-python','azureml-defaults','joblib','azureml-automl-runtime'], 
                              conda_packages=['numpy==1.16.2',
                                             'pandas<=0.23.4,>=0.21.0',
                                             'scikit-learn<=0.20.3,>=0.19.0'], 
                              pin_sdk_version=True)
cd.add_pip_package('azureml-explain-model')

**Comment by ram-msft** [comment]
@electrozoa Thanks for the question. We will update you shortly.

**Comment by electrozoa** [comment]
> @electrozoa Thanks for the question. We will update you shortly.

Hi Ram, can you please provide an update on this? I am really struggling with this issue.

**Comment by jadhosn** [comment]
@electrozoa could this be something similar to [this](https://github.com/Azure/MachineLearningNotebooks/issues/128#issuecomment-613242815)?
