### ISSUE TITLE
SQL Datastore Error Messages

### ISSUE THREAD

**Issue by svickers** [Azure/MachineLearningNotebooks#948]
Any number of sql exceptions seem to get rolled up into one relatively unhelpful error message: 

```
azureml.data.dataset_error_handling.DatasetValidationError: Cannot load any data from the datastore using the SQL query "{}". Please make sure the datastore and query is correct.
```

This same exception happens when there is a sql syntax error, query timeout, deadlock, and other times where we haven't been able to pinpoint the cause without any specifics.  

Full stack trace:

```
Traceback (most recent call last):
  File "C:\Users\scott\Anaconda3\envs\myenv\lib\site-packages\azureml\data\dataset_error_handling.py", line 45, in _validate_has_data
    dataflow.verify_has_data()
  File "C:\Users\scott\Anaconda3\envs\myenv\lib\site-packages\azureml\dataprep\api\_loggerfactory.py", line 149, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\scott\Anaconda3\envs\myenv\lib\site-packages\azureml\dataprep\api\dataflow.py", line 845, in verify_has_data
    profile = self.take(1)._get_profile()
  File "C:\Users\scott\Anaconda3\envs\myenv\lib\site-packages\azureml\dataprep\api\dataflow.py", line 548, in _get_profile
    include_string_lengths)
  File "C:\Users\scott\Anaconda3\envs\myenv\lib\site-packages\azureml\dataprep\api\dataprofile.py", line 53, in _from_execution
    inspector_response = _Inspector._from_execution(engine_api, context, table_inspector)
  File "C:\Users\scott\Anaconda3\envs\myenv\lib\site-packages\azureml\dataprep\api\inspector.py", line 219, in _from_execution
    row_count = _MAX_ROW_COUNT))
  File "C:\Users\scott\Anaconda3\envs\myenv\lib\site-packages\azureml\dataprep\api\_aml_helper.py", line 38, in wrapper
    return send_message_func(op_code, message, cancellation_token)
  File "C:\Users\scott\Anaconda3\envs\myenv\lib\site-packages\azureml\dataprep\api\engineapi\api.py", line 104, in execute_inspector
    response = self._message_channel.send_message('Engine.ExecuteInspector', message_args, cancellation_token)
  File "C:\Users\scott\Anaconda3\envs\myenv\lib\site-packages\azureml\dataprep\api\engineapi\engine.py", line 120, in send_message
    raise_engine_error(response['error'])
  File "C:\Users\scott\Anaconda3\envs\myenv\lib\site-packages\azureml\dataprep\api\errorhandlers.py", line 24, in raise_engine_error
    raise ExecutionError(error_response)
azureml.dataprep.api.errorhandlers.ExecutionError: Could not execute provided query.|session_id=524db3d5-bf61-4e18-b249-fc14c01e5ef4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eval-loop.py", line 42, in <module>
    df_predict = data.get_unlinked(country,1000,classifier,run_id)
  File "C:\Users\scott\Documents\keepitclassy\categories\data.py", line 97, in get_unlinked
    ds = Dataset.Tabular.from_sql_query((sql_server, sql))
  File "C:\Users\scott\Anaconda3\envs\myenv\lib\site-packages\azureml\data\_loggerfactory.py", line 78, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\scott\Anaconda3\envs\myenv\lib\site-packages\azureml\data\dataset_factory.py", line 381, in from_sql_query
    _validate_has_data(dataflow, 'Cannot load any data from the datastore using the SQL query "{}". '
  File "C:\Users\scott\Anaconda3\envs\myenv\lib\site-packages\azureml\data\dataset_error_handling.py", line 48, in _validate_has_data
    raise DatasetValidationError(error_message)
azureml.data.dataset_error_handling.DatasetValidationError: Cannot load any data from the datastore using the SQL query "{}". Please make sure the datastore and query is correct.
```

**Comment by MayMSFT** [comment]
thanks for the feedback. we are tracking this as a bug for improvement.

**Comment by SturgeonMi** [comment]
Hi Scott,
We are working on exposing the actual error message to improve the experience.
Will reach out when the fix is completed.

**Comment by anliakho2** [comment]
Hi @svickers, this is true and we are aware of suboptimal experience. We are rolling out new version of the SDK in couple of weeks with much improved error handling.
For instance find below an example of incorrect query syntax and wrong table name error output in the development branch right now:
`
Error Code: ScriptExecution.DatabaseQuery
Failed Step: 0ac7eadb-0bca-4585-85eb-45f3a9459be2
Error Message: ScriptExecutionException was caused by DatabaseQueryException.
  'MSSQL' encountered exception of with error code '-2146232060' while executing query 'SELECT * FROM (SELECT ;top 100 * FROM [SalesLT].[Bogus]) as subquery'. SqlException class: 15
    Incorrect syntax near ';'.

Error Code: ScriptExecution.DatabaseQuery
Failed Step: c678d6eb-4e03-4563-98fa-e67d829707bb
Error Message: ScriptExecutionException was caused by DatabaseQueryException.
  'MSSQL' encountered exception of with error code '-2146232060' while executing query 'SELECT * FROM (SELECT top 100 * FROM [SalesLT].[Bogus]) as subquery'. SqlException class: 16
    Invalid object name 'SalesLT.Bogus'.
`
As you can see we now print actual query, error code, error class and actual error message from the server. Hope this helps.

**Comment by svickers** [comment]
@anliakho2 Looking forward to it, that will be very helpful.

**Comment by anliakho2** [comment]
@svickers We have released the new version of `azureml-dataprep`
[link to pypi](https://pypi.org/project/azureml-dataprep/1.6.0/)

If you want you can try it and let us know if this resolves your issue.
Thanks !

**Comment by svickers** [comment]
> @svickers We have released the new version of `azureml-dataprep`
> [link to pypi](https://pypi.org/project/azureml-dataprep/1.6.0/)
> 
> If you want you can try it and let us know if this resolves your issue.
> Thanks !

Yes, much better!
