### ISSUE TITLE
permissions issue

### ISSUE THREAD

**Issue by guybartal** [Azure/MachineLearningNotebooks#96]
I've tried to get Workspace from config which I do have access to, but it fails with the following error:
SDK version: 0.1.80
Found the config file in: C:\Users\gubert\Repos\Gimmonix\HotelMappingAI\aml_config\config.json
get_workspace error using subscription_id=xxxxxxxxxxxxxxxxxxxxxxx, resource_group_name=xxxxxxxxxxxx, workspace_name=gmx-ml-mapping
Traceback (most recent call last):
  File "C:\Users\gubert\.azureml\envs\myenv\lib\site-packages\azureml\_project\_commands.py", line 320, in get_workspace
    workspace_name)
  File "C:\Users\gubert\.azureml\envs\myenv\lib\site-packages\azureml\_base_sdk_common\workspace\operations\workspaces_operations.py", line 78, in get
    raise models.ErrorResponseWrapperException(self._deserialize, response)
azureml._base_sdk_common.workspace.models.error_response_wrapper.ErrorResponseWrapperException: Operation returned an invalid status code 'Forbidden'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\gubert\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd_launcher.py", line 38, in &lt;module&gt;
    main(sys.argv)
  File "c:\Users\gubert\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\__main__.py", line 265, in main
    wait=args.wait)
  File "c:\Users\gubert\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\__main__.py", line 256, in handle_args
    run_main(addr, name, kind, *extra, **kwargs)
  File "c:\Users\gubert\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\_local.py", line 52, in run_main
    runner(addr, name, kind == 'module', *extra, **kwargs)
  File "c:\Users\gubert\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\runner.py", line 32, in run
    set_trace=False)
  File "c:\Users\gubert\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 1283, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "c:\Users\gubert\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 1290, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "c:\Users\gubert\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\_pydev_imps\_pydev_execfile.py", line 25,
in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "c:\Users\gubert\Repos\Gimmonix\HotelMappingAI\test.py", line 8, in &lt;module&gt;
    ws = Workspace.from_config()
  File "C:\Users\gubert\.azureml\envs\myenv\lib\site-packages\azureml\core\workspace.py", line 153, in from_config
    auth=auth)
  File "C:\Users\gubert\.azureml\envs\myenv\lib\site-packages\azureml\core\workspace.py", line 86, in __init__
    auto_rest_workspace = _commands.get_workspace(auth, subscription_id, resource_group, workspace_name)
  File "C:\Users\gubert\.azureml\envs\myenv\lib\site-packages\azureml\_project\_commands.py", line 326, in get_workspace
    resource_error_handling(response_exception, WORKSPACE)
  File "C:\Users\gubert\.azureml\envs\myenv\lib\site-packages\azureml\_base_sdk_common\common.py", line 270, in resource_error_handling
    raise ProjectSystemException(response_message)
azureml.exceptions._azureml_exception.ProjectSystemException: {
    "error_details": {
        "error": {
            "code": "AuthorizationFailed",
            "message": "The client 'xxxxxxxxxx@microsoft.com' with object id 'xxxxxxxxxxxxx' does not have authorization to perform action 'Microsoft.MachineLearningServices/workspaces/read' over scope '/subscriptions/xxxxxxxxxxxxxx/resourceGroups/CarsolizeCloud - Test Global/providers/Microsoft.MachineLearningServices/workspaces/gmx-ml-mapping'."
        }
    },
    "status_code": 403,
    "url": "https://management.azure.com/subscriptions/xxxxxxxxxxxxx/resourceGroups/CarsolizeCloud%20-%20Test%20Global/providers/Microsoft.MachineLearningServices/workspaces/gmx-ml-mapping?api-version=2018-03-01-preview"
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f93a584-8199-d04b-788e-53ce99ef483a
* Version Independent ID: c1ee7a99-6d4b-3763-446a-912077183ccb
* Content: [azureml.core.workspace.Workspace class](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.workspace.workspace?view=azure-ml-py#from-config-path-none--auth-none-)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.workspace.Workspace.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.workspace.Workspace.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by guybartal** [comment]
I'll double check and update you, but i'm 99% sure I was logged in. may be conda env issue.

**Comment by guybartal** [comment]
My bad... you can close the issue, sorry!
