### ISSUE TITLE
Error submitting jobs using hyperdrive

### ISSUE THREAD

**Issue by Yi-Mao** [Azure/MachineLearningNotebooks#97]
Here is the error message:

Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/wstorontbatchai_dpvnbyza/azureml/nl2sq_1543173288196_1/mounts/azureml_project_share/azureml/container_control_script_nl2sq_1543173288196_1.py", line 195, in <module>
    project_fetcher.fetch_project_snapshot(options.snapshot)
  File "/mnt/batch/tasks/shared/LS_root/jobs/wstorontbatchai_dpvnbyza/azureml/nl2sq_1543173288196_1/mounts/azureml_project_share/azureml/nl2sq_1543173288196_1/azureml-setup/project_fetcher.py", line 49, in fetch_project_snapshot
    _download_tree(sas_tree, ["."])
  File "/mnt/batch/tasks/shared/LS_root/jobs/wstorontbatchai_dpvnbyza/azureml/nl2sq_1543173288196_1/mounts/azureml_project_share/azureml/nl2sq_1543173288196_1/azureml-setup/project_fetcher.py", line 97, in _download_tree
    _download_tree(child, path_stack)
  File "/mnt/batch/tasks/shared/LS_root/jobs/wstorontbatchai_dpvnbyza/azureml/nl2sq_1543173288196_1/mounts/azureml_project_share/azureml/nl2sq_1543173288196_1/azureml-setup/project_fetcher.py", line 89, in _download_tree
    fh.write(_read_response(response))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 12403-12405: ordinal not in range(128)

**Comment by rastala** [comment]
Could you post your workspace name and Azure region, as well as the command you used to submit the run?
